### ISSUE TITLE
How to diable main account sniping ?

### ISSUE THREAD

**Issue by Tenclea** [Vedza/NitroSniperGo#101]
You should make an option to disable sniping on the main account

**Comment by Tenclea** [comment]
i'm sorry i did not see this was already implemented

**Comment by Tenclea** [comment]
Actually, if anyone sees this, could you tell me how to disable sniping on the main account, I can't seem to find any information on this anywhere

**Comment by Vedza** [comment]
Hi, I don't understand your issue. The all point of the sniper is to claim nitro on main account

**Comment by Tenclea** [comment]
Hi, I'm sorry, I meant the main account is always shown as online, and thus even when changing the "main_status" option in the settings, we wont be able to receive, for example, notifications on mobile.
It would be great if we could disable sniping on the main account, but keep it enabled on the alt accounts, which would redirect the codes to the main token if they ever find one.

I hope I was a little bit more clear this time.

**Comment by Vedza** [comment]
Oh ok I didn't know about this issue, I'll add this later

**Comment by Tenclea** [comment]
Thank you, and congratulations for your work so far :)

**Comment by Vedza** [comment]
I just added this feature !
