### ISSUE TITLE
Dm after giveaway win

### ISSUE THREAD

**Issue by Tasnemo** [Vedza/NitroSniperGo#103]
Whenever I win a giveaway it doesn't Dm the giveaway host, but I have enabled the option to Dm host after win. These asre my giveaway settings.
 "nitro_giveaway_sniper": true,
  "giveaway_delay": 0,
  "giveaway_dm": "can I get my prize, thank you",
  "giveaway_dm_delay": 0,
  "privnote_sniper": true,
  "invite_sniper": true,
  "invite_delay": {
    "min": 10,
    "max": 20

**Comment by Vedza** [comment]
Hi, can you send me what message said that you win ? To understand why it didn't send the dm
