### ISSUE TITLE
Cant start the heroku app

### ISSUE THREAD

**Issue by brams1441** [Vedza/NitroSniperGo#109]
Hello, when i attempt to start the app in heroku i get this error. Do you know how i could fix this?

`2021-01-12T16:32:00.700884+00:00 app[worker.1]: 16:32:00 [x] Failed to parse JSON file:  invalid character '\n' in string literal`

**Comment by Vedza** [comment]
There is an error in your settings like a missing `"` or  a `,` without anything after

**Comment by DarkGD123** [comment]
I have this problem as well but instead its `end input`

**Comment by Vedza** [comment]
If you have `Failed to parse JSON file` error it's always a mistyping or a wrong character somewhere.
