### ISSUE TITLE
Bug with winning a giveaway

### ISSUE THREAD

**Issue by Ender786** [Vedza/NitroSniperGo#120]
I found a bug where if i am using the sniper and someone tags on discord me and says giveaway won it says i won a giveaway and sends a notification through the webhook saying i won, maybe make it so that it detects if only a bot says I have a won a giveaway.

**Comment by Vedza** [comment]
If someone tags you and say that you won a giveaway then unless he is trolling you probably won a giveaway, but if you want to detect only messages from bot then I'll check tonight if I can check if user is a bot

**Comment by Ender786** [comment]
thanks man I appreciate it you do really care about this project keep up the good work 👍

**Comment by Ender786** [comment]
![image](https://user-images.githubusercontent.com/54211493/104586491-7207e780-565d-11eb-9164-4f55a0777274.png)

**Comment by Vedza** [comment]
Done
