### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Anceph** [Vedza/NitroSniperGo#121]
I just tried and worked like 30 minutes ago but i wanted to change the tokens. When i did it, i couldn't make it work again. Same on Heroku.

![image](https://user-images.githubusercontent.com/41387237/104596069-86aba600-5684-11eb-94b8-deb5bff0d0bb.png)

**Comment by Vedza** [comment]
Hi, If you enabled 2fa or change your password your token also changed.
And if you already have 2fa enabled your token might have changed.

**Comment by Anceph** [comment]
It may have changed, let me check it out.

**Comment by Anceph** [comment]
Yeah changed, thanks.
