### ISSUE TITLE
New subscription required to redeem gift.

### ISSUE THREAD

**Issue by MrJCJ** [Vedza/NitroSniperGo#122]
Hey there, 
I've been getting "New subscription required to redeem gift." for a few times now, could you tell me, what causes this and how to fix this?
regards.

**Comment by Vedza** [comment]
Hey,
I'm sorry I can't help you as I don't know either.

**Comment by YTisRuler2006** [comment]
Same i need hep too

**Comment by YTisRuler2006** [comment]
This only happens with this sniper

**Comment by Vedza** [comment]
Maybe because other snipers print something else, but it's probably the same

**Comment by YTisRuler2006** [comment]
but it says i need to link my payment info to claim the gift

**Comment by Vedza** [comment]
Then if you add a payment source it will either redeem the code or print a different error

**Comment by Tenclea** [comment]
Might be because the user trying to claim the gift code already has another subscription enabled ?
(Redeeming nitro boost when you have nitro classic for example)

**Comment by Vedza** [comment]
Yes maybe it's not possible any more, but I already claimed Nitro classic while I had a boost in the past. It just went to credit like that.
![image](https://user-images.githubusercontent.com/28839427/104807976-36972580-57e3-11eb-9925-8b6f4fbb2e5d.png)

**Comment by RocketNinja15** [comment]
Same, i also have this issue

**Comment by k6d** [comment]
when you snipe a **xbox game pass nitro** but you had nitro before you get this error
