### ISSUE TITLE
error when trying to run app with termux

### ISSUE THREAD

**Issue by maalos** [Vedza/NitroSniperGo#123]
![Screenshot_2021-01-14-21-11-40-73.jpg](https://user-images.githubusercontent.com/54448857/104644055-e5682400-5672-11eb-9f3d-e1df7897b2a5.jpg)

trust me, i have both tokens right in my settings, they're copied from my repl that worked

**Comment by Vedza** [comment]
You must cd to the folder so .json is on the same working directory

**Comment by maalos** [comment]
im not stupid, termux just doesnt display it

**Comment by maalos** [comment]
![Screenshot_2021-01-14-21-48-48-01.jpg](https://user-images.githubusercontent.com/54448857/104647535-a25c7f80-5677-11eb-9a2a-fa83a869544a.jpg)

**Comment by maalos** [comment]
its kind of like it has to refresh??

**Comment by Vedza** [comment]
Lol I didn't say you are stupid, send me your discord if you want me to help you

**Comment by maalos** [comment]
i didnt say you said im stupid either, but whatever. maalos#9853
