### ISSUE TITLE
Cannot deploy to heroku

### ISSUE THREAD

**Issue by UltraTV** [Vedza/NitroSniperGo#124]
I'm not able to deploy the project to heroku with the button here on github.
It either says "There is an error" or it says that app.json is missing

**Comment by Vedza** [comment]
It works for me 🤔, can you send me the link it opens when you click on the button ?

**Comment by UltraTV** [comment]
Weird, looks like it works now. Yesterday it wasn't working, maybe it was a problem on herokus side?

**Comment by Vedza** [comment]
Probably as I didn't edit anything since
