### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Dand2550** [Vedza/NitroSniperGo#126]
I wanted to ask if Is it normal that the sniper only sends DMs in some giveaways that are won and not in others?
For example:
Giveaway 1: I win
The sniper dm to the host
Giveaway 2: I win
The sniper never dmed to the host

Is it an error, or do I have to configure something specific?
(I have the delay to a minimum)

**Comment by Vedza** [comment]
It's normal, there is a multiple giveaway bot, and they don't say the same things when you win a giveaway. So sometimes the sniper understand that you won one because a bot use the words "won" "giveaway" and tag you but doesn't find the giveaway host in the message.

**Comment by Dand2550** [comment]
I think it is because some draws I come out as the first winner and in others they reroll.
I said that because all the giveaways is with the same bot: 
![image](https://user-images.githubusercontent.com/77521090/104827123-9368ff00-5828-11eb-8e3b-10fc535bf7b8.png)

When it happen: 
![image](https://user-images.githubusercontent.com/77521090/104827137-c90de800-5828-11eb-8f26-600d25a4bc37.png)
The sniper notifies me that I won, but never dmed to the host


If I'm right, it would be great if the sniper send dm when they reroll and you win
