### ISSUE TITLE
An error when I start the Sniper

### ISSUE THREAD

**Issue by Aki26-GamePlay** [Vedza/NitroSniperGo#127]
Hi!
When I start Sniper it welcomes me:
![image](https://user-images.githubusercontent.com/64480571/104810754-212bf680-57f7-11eb-95ac-2efeb9bf7d85.png)
Why is that? Can I fix it somehow?

**Comment by Vedza** [comment]
Hi, 
This error doesn't affect the sniper, it just happens because it's a self bot. And it's hard for me to fix it because I don't have this error, so I can't test it.

**Comment by Aki26-GamePlay** [comment]
OK thank you. I can handle it, I just thought I'd speak.
