### ISSUE TITLE
 The privnote sniper will send the sniped text

### ISSUE THREAD

**Issue by Aki26-GamePlay** [Vedza/NitroSniperGo#128]
If the sniper finds a privnote link, send the text in it to the webhook and even to the console.

**Comment by Vedza** [comment]
It already sends to webhook and also put the content in a file.
But privnote sniper is a bit broken rn.

**Comment by Aki26-GamePlay** [comment]
I test it, and it doesn't send anything

**Comment by Vedza** [comment]
Then it either crashed like the opened issue or it's disabled in the settings.

**Comment by Aki26-GamePlay** [comment]
And if I run sniper on heroku, how do I find the file?

**Comment by Aki26-GamePlay** [comment]
> Then it either crashed like the opened issue or it's disabled in the settings.

How can i re-enable?

**Comment by Vedza** [comment]
> > Then it either crashed like the opened issue or it's disabled in the settings.
> 
> How can i re-enable?

Read the readme



> And if I run sniper on heroku, how do I find the file?

Run `cat privnotes.txt` in run console

**Comment by Aki26-GamePlay** [comment]
> > > Then it either crashed like the opened issue or it's disabled in the settings.
> > 
> > 
> > How can i re-enable?
> 
> Read the readme

I have already enabled the privnote section and it also appears properly in the console, but it doesn't send the text anywhere, only to the file.

**Comment by Aki26-GamePlay** [comment]
> > And if I run sniper on heroku, how do I find the file?
> 
> Run `cat privnotes.txt` in run console
It write's this in the run section: "cat: privnotes.txt: No such file or directory"

**Comment by Vedza** [comment]
> Then it either crashed like the opened issue or it's disabled in the settings.

> > > And if I run sniper on heroku, how do I find the file?
> > 
> > 
> > Run `cat privnotes.txt` in run console
> > It write's this in the run section: "cat: privnotes.txt: No such file or directory"

So it crashed, I'm working on this issue right now

**Comment by Aki26-GamePlay** [comment]
> > > Run `cat privnotes.txt` in run console
> > It write's this in the run section: "cat: privnotes.txt: No such file or directory"
> 
> So it crashed, I'm working on this issue right now

Thank you :)

**Comment by Aki26-GamePlay** [comment]
@Vedza It's not send anything to the webhook, and it can't open the privnotes.txt
![image](https://user-images.githubusercontent.com/64480571/104852293-5ff6a500-58fa-11eb-8475-451c7ac26070.png)

**Comment by Vedza** [comment]
> @Vedza It's not send anything to the webhook, and it can't open the privnotes.txt
> ![image](https://user-images.githubusercontent.com/64480571/104852293-5ff6a500-58fa-11eb-8475-451c7ac26070.png)

Pls read previous messages

**Comment by Aki26-GamePlay** [comment]
> > @Vedza It's not send anything to the webhook, and it can't open the privnotes.txt
> > ![image](https://user-images.githubusercontent.com/64480571/104852293-5ff6a500-58fa-11eb-8475-451c7ac26070.png)
> 
> Pls read previous messages

I read it but when this is repaired?

**Comment by Vedza** [comment]
I'll do that when I have the time to. I'm not getting paid to work on this sniper and have some works for school and work. I'm not always going to fix issues in the hour/day

**Comment by Aki26-GamePlay** [comment]
I'm sorry, I didn't mean to urge you

**Comment by Vedza** [comment]
No problem, I just want to make things clear if someone else sees that issue
