### ISSUE TITLE
[Suggestion...]

### ISSUE THREAD

**Issue by sonicm35** [Vedza/NitroSniperGo#134]
Hey...
Can you add support for __**https://repl.it/**__ as like heroku...
i mean, want to host that code on repl.it...
How can i do that?
or add some details in README.

**Comment by Vedza** [comment]
I don't use repl.it, so I can't help you. But why don't you use heroku ?

**Comment by Ender786** [comment]
All repl.it projects are public so anyone can view them unless you pay for it so if you were to use repl.it people would be able to see your token and with your token they can log into your account

**Comment by sonicm35** [comment]
> All repl.it projects are public so anyone can view them unless you pay for it so if you were to use repl.it people would be able to see your token and with your token they can log into your account

Nope...
I have Premium plan, so all of minr repls are Private.

**Comment by Vedza** [comment]
[Deploy on Repl.it](https://repl.it/github/Vedza/NitroSniperGo) ( ⚠️ Only use this option if you can have private repls)
