### ISSUE TITLE
Failed to read file settings.json

### ISSUE THREAD

**Issue by DueHack12** [Vedza/NitroSniperGo#136]
![Screen Shot 2021-01-20 at 2 56 12 PM](https://user-images.githubusercontent.com/63979352/105227724-a54fe800-5b2f-11eb-9adf-5e345aa41053.png)

**Comment by Vedza** [comment]
It means there is not the settings file where you're running the exe.

**Comment by DueHack12** [comment]
but i have the file in the same folder

**Comment by DueHack12** [comment]
![Screen Shot 2021-01-20 at 3 02 02 PM](https://user-images.githubusercontent.com/63979352/105228327-75551480-5b30-11eb-8357-79512473cf55.png)

**Comment by Vedza** [comment]
You must change directory to the build folder before running it

**Comment by DueHack12** [comment]
What do you mean by that

**Comment by Vedza** [comment]
How do you run it ?

**Comment by DueHack12** [comment]
i click on the exec file

**Comment by DueHack12** [comment]
i also tried calling it direcly in my terminal

**Comment by Vedza** [comment]
`cd ~/your-folder/NitroSniperGo_build_mac/ && ./NitroSniperGo`

**Comment by DueHack12** [comment]
It works now, thanks so much

**Comment by Vedza** [comment]
I updated it, you can now run it from anywhere or just click on it
