### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Bandito111** [Vedza/NitroSniperGo#138]
Well can u make the sniper give a HTTPS link like this so we can host the repl.it on uptimerobot.com which is far more easier and better than heroku, just a suggestion 
![image](https://user-images.githubusercontent.com/28823858/105316784-5c5b6a80-5be7-11eb-9986-6e7eff43e7b9.png)

**Comment by trqphy** [comment]
How do I make it so I can use with repl?
