### ISSUE TITLE
Let us host it on repl.it using https link

### ISSUE THREAD

**Issue by Bandito111** [Vedza/NitroSniperGo#139]
Can you add a piece of code such that it gives this HTTPS link while on repl.it so that we can host the repl on uptimerobot.com, this way it will be much easier for less tech savvy people and is much less complicated than deploying it on heroku. 
 ![image](https://user-images.githubusercontent.com/28823858/105317265-05a26080-5be8-11eb-861d-93bdfa79c0c5.png)

I can give u a link to a python discord nitro sniper so you can get a idea on how it will work. Just a simple suggestion :)

**Comment by Vedza** [comment]
The problem with replit is that if you don't have a premium plan, everybody will see your token. And heroku is really easy to use, you just have to click on the button and enable sniper in resources.

**Comment by Bandito111** [comment]
> The problem with replit is that if you don't have a premium plan, everybody will see your token. And heroku is really easy to use, you just have to click on the button and enable sniper in resources.

Well I have a premium plan XD

**Comment by Vedza** [comment]
Yeah but I'm sure some people without premium will still put it on replit. I already put replit file so you can run but didn't know you need to add a web server. I'll check that later

**Comment by Flare404** [comment]
you can put the token in a .env

**Comment by Vedza** [comment]
That's already what I did for Heroku. But I don't know how to select a specific branch in .replit and if the web server is mandatory to host it 24/7

**Comment by sonicm35** [comment]
> Can you add a piece of code such that it gives this HTTPS link while on repl.it so that we can host the repl on uptimerobot.com, this way it will be much easier for less tech savvy people and is much less complicated than deploying it on heroku.
> ![image](https://user-images.githubusercontent.com/28823858/105317265-05a26080-5be8-11eb-861d-93bdfa79c0c5.png)
> 
> I can give u a link to a python discord nitro sniper so you can get a idea on how it will work. Just a simple suggestion :)

Yes... Repl.it is much better... & i also want that... i have premium plan on repl.it... xD

**Comment by NotSwaraj** [comment]
Check the pull request I sent. Krnl

**Comment by Vedza** [comment]
I still don't know if the web server is mandatory to host on replit. There is a repl.it config file, so you can run it on replit if you want, I just won't put a big button in the README so people w/o premium plan won't use it.
