### ISSUE TITLE
[Suggestion] Play a sound when Nitro been claimed

### ISSUE THREAD

**Issue by guuh4xx** [Vedza/NitroSniperGo#145]
Hi, would be nice if the software play a sound when Nitro has been claimed, like a hitsound or something...

It will be useful for those who leave this sniper in background.

**Comment by SloppyPuppy** [comment]
Agreed, if that's a thing that won't take long to implement, I'd like to
see that too, and thanks Vedza for keeping the project alive, I'm still
sniping even today :).

пон, 25. јан 2021. у 23:05 guuhfx <notifications@github.com> је написао/ла:

**Comment by Vedza** [comment]
Added 👍 Thanks for your suggestion !
