### ISSUE TITLE
claim time

### ISSUE THREAD

**Issue by pIague** [Vedza/NitroSniperGo#149]
yo, just a little suggestion i think would be handy would be after it snipes a code it would say how fast it sniped the code in the log?

**Comment by Vedza** [comment]
Hey,
In your settings you must enable `delay`
```json5
...
 "nitro": {
    "max": 2, 
    "cooldown": 24,  
    "main_sniper": true 
    "delay": true //<--- HERE
...
```

**Comment by pIague** [comment]
o thanks g
