### ISSUE TITLE
v3.0 (Linux version) No files in the zip file

### ISSUE THREAD

**Issue by JonasBBX** [Vedza/NitroSniperGo#150]
The size is 202kb and inside the folder is nothing??
Maybe you forgot to upload the files im not sure but please fix asap. :)

**Comment by Vedza** [comment]
Hey, 
There is a compilation error for linux. I suggest you to download the previous version, and I'll update here when I find a solution.

**Comment by Vedza** [comment]
Fixed

**Comment by JonasBBX** [comment]
> Fixed

tysm man appreciate your work
