### ISSUE TITLE
Token Authentication Error on Startup [Mac]

### ISSUE THREAD

**Issue by tuckMCWizard** [Vedza/NitroSniperGo#151]
Hi, I keep getting this error upon starting up the program, I don't know why, I've even tried switching through a few of my alts but it's still giving the same error.

[x] Error opening connection for [token], websocket: close 4004: Authentication failed.

**Comment by Vedza** [comment]
Hi,
Your token must have changed, because this error only happen when your token isn't working.

**Comment by tuckMCWizard** [comment]
I realized I was using the wrong code, my bad
