### ISSUE TITLE
v3.0 (Linux) Sound not working

### ISSUE THREAD

**Issue by JonasBBX** [Vedza/NitroSniperGo#156]
no sound plays when nitro code sniped.

**Comment by Vedza** [comment]
It plays a sound when the code is applied. Did you get a nitro ?

**Comment by JonasBBX** [comment]
> It plays a sound when the code is applied. Did you get a nitro ?

oh, also someone sent me nitro code in dms and it didnt even claim and the code was somehow accepted and i didnt get it
sorry about this issue i thought that any nitro code sniped would play a sound

**Comment by Vedza** [comment]
What the sniper said ? If it said already redeemed then you got a already redeemed link

**Comment by JonasBBX** [comment]
> What did the sniper said ? If it said already redeemed then you got a already redeemed link

nope it said nothing at all

**Comment by Vedza** [comment]
But it claimed the code for you ?

**Comment by JonasBBX** [comment]
> But it claimed the code for you ?

nope but i had the sniper open so it should have said something in logs right?

**Comment by Vedza** [comment]
Yeah it should. I just tested it and it worked for me. 🤔

**Comment by JonasBBX** [comment]
> Yeah it should. I just tested it and it worked for me. 🤔

thats weird btw have you got any spare codes ive been trying all day and nothing oof no worries if not
