### ISSUE TITLE
Giveaway people are getting smart

### ISSUE THREAD

**Issue by tuckMCWizard** [Vedza/NitroSniperGo#157]
Left this running overnight, and found that I would've won 2 giveaways, except that the people I claimed it from wanted another message to be sent or I would not receive the nitro. Is there any current way in the program to do this or does this need to be added? If the latter I recommend to have it send another message after they reply a few times and the replies they sent do not contain a code.

![Screen Shot 2021-01-31 at 12 09 52 PM](https://user-images.githubusercontent.com/77516066/106396529-5a4e9400-63bd-11eb-8cb7-b63697a0f3b8.png)

**Comment by FeelsBadMan1** [comment]
This would be sexy af it it where added

**Comment by Vedza** [comment]
I think it would be too hard to detect that the host replied with that type of question, and reply something related to his questions. And on top of that without having false positive. Host will detect that you're a self bot and report you for sure.
