### ISSUE TITLE
Non Fatal Error (Program still works it just irritates me)

### ISSUE THREAD

**Issue by yuhsecurity** [Vedza/NitroSniperGo#161]
2021/02/05 14:44:00 [DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string
-
Not sure what this means but uh, yeah. after showing this the sniper runs fine it just bugs me because it shows up everytime i run it and its mildly irritating

**Comment by Vedza** [comment]
https://github.com/Vedza/NitroSniperGo#known-issues
