### ISSUE TITLE
Servers count not right on start

### ISSUE THREAD

**Issue by Tenclea** [Vedza/NitroSniperGo#165]
Something I noticed some time ago (not that important if you ask me), but that could be fixed is the fact that whenever I start the sniper with multiple alt accounts, the servers count on the start message log is wrong, most likely because only one account was counted.

It'd be great if this could be fixed, even though it is not an emergency at all ! :)

**Comment by FokshaWasTaken** [comment]
this can't be fixed iirc, but dunno maybe it could

**Comment by FeelsBadMan1** [comment]
> Something I noticed some time ago (not that important if you ask me), but that could be fixed is the fact that whenever I start the sniper with multiple alt accounts, the servers count on the start message log is wrong, most likely because only one account was counted.
> 
> It'd be great if this could be fixed, even though it is not an emergency at all ! :)

hmm. for me it tells sniping on 209 Servers with 9 Accounts. 1 account maximal could join 100 Servers so its not a falsecount

**Comment by Vedza** [comment]
Yeah sometime discord api return an empty list of servers. I guess it's random, so I'd say I can't do anything about that.
