### ISSUE TITLE
I didnt get how the nitro sniper works

### ISSUE THREAD

**Issue by wowyourbad** [Vedza/NitroSniperGo#173]
so I ran it but then it just says sniped the code but what do I do now with the code?

**Comment by wowyourbad** [comment]
how does it work?

**Comment by Vedza** [comment]
It just says when the bot finds a code then what was the result after trying to claim it automatically. It could either be a fake link, already redeemed or redeemed for you. 
If you see something like that `[+] Nitro applied : Nitro Classic`, then you got free Nitro
