### ISSUE TITLE
Multiple-Alts support

### ISSUE THREAD

**Issue by EmperorMeow30** [Vedza/NitroSniperGo#174]
How many alt accounts that this support? Does it only supports 2 accounts?If Yes, can you please add Multi-Alts support for the following updates. Thanks for this magnificent work.

(Issue fixed a while ago, friend helped me to set the stuffs)

**Comment by Vedza** [comment]
You can put as many accounts as you want 
```json5
"alts": [ // Alts token
      "Token1",
      "Token2",
      "Token3"
    ]
````
