### ISSUE TITLE
Error 401 : Unauthorized

### ISSUE THREAD

**Issue by Spinicle** [Vedza/NitroSniperGo#175]
I keep getting this on my alt, `Error 401 : Unauthorized` (The response in the webhook), why does this happen and how can i fix it?

EDIT - My friend sent a claimed code but it did not show up in the logs of my main account.. HELP

**Comment by Vedza** [comment]
https://github.com/Vedza/NitroSniperGo#known-issues

*It looks like Discord added a security feature where your token change every time but also expire with 2FA, that might be the reason why the sniper doesn't work after some time or if you get an unauthorized error when sniping Nitro*
