### ISSUE TITLE
I dont know what program to run .go with

### ISSUE THREAD

**Issue by GreenJorgi** [Vedza/NitroSniperGo#179]

**Comment by Vedza** [comment]
https://github.com/Vedza/NitroSniperGo#usage

You have multiple choices to run the sniper : 

- [Deploy on Heroku](https://heroku.com/deploy?template=https://github.com/Vedza/NitroSniperGo/tree/heroku) (Free 24/7)
   * Deploy
   * Resources -> enable sniper
   * See logs in More -> View logs

- Download the latest [release](https://github.com/Vedza/NitroSniperGo/releases)
