### ISSUE TITLE
what does this mean i am using repl.it i have premium it says this 

### ISSUE THREAD

**Issue by bluezar54** [Vedza/NitroSniperGo#181]
what does this mean and also idk why it isnt dming the owner 
[
![image](https://user-images.githubusercontent.com/68278932/108322229-3ecfef80-71eb-11eb-9f99-796221d94aba.png)
](url)
![image](https://user-images.githubusercontent.com/68278932/108324584-1990b080-71ee-11eb-80ae-b5b1329f22a4.png)

**Comment by Vedza** [comment]
https://github.com/Vedza/NitroSniperGo/issues?q=is%3Aissue+is%3Aclosed+rate+limited

**Comment by Vedza** [comment]
and about dm, the sniper doesn't work with every giveaway bot
