### ISSUE TITLE
Check if giveaway host is a user or bot.

### ISSUE THREAD

**Issue by rednek46** [Vedza/NitroSniperGo#182]
I reviewed your python code and saw that the snipper checks for the string “ **giveaway**, react with, giveaway”. And reacts to it to enter the giveaway. One major issue with this is that any user can send the above string to the chat and identify the sniper account. It would be best to add a check and make sure that the person who sends the giveaway is a bot rather than a user. I don’t know much about GO or I’d have made a pull request.

**Comment by Vedza** [comment]
Hi,
It's already what the sniper does.

**Comment by rednek46** [comment]
@Vedza ok then the snipper user I tested this with may have Older version of the snipper or is using the the python code.

**Comment by Vedza** [comment]
I added that here 8dfbf75e43f62412d6494dc6e72e76733d9f8906 and it was released on 2.7

**Comment by rednek46** [comment]
Nice. My bad I only looked into the python code.
