### ISSUE TITLE
webhook not working?

### ISSUE THREAD

**Issue by Hackermanlmao** [Vedza/NitroSniperGo#184]
I'm probably doing something wrong, in the settings file I have a webhook url, I know it's correct and working, and I have good_only set to false. But whenever I snipe a code/privnote, it doesn't send anything to the webhook. Everything else works good though

**Comment by Vedza** [comment]
Try to disable privnote sniper. Sometimes it makes the program crash.

**Comment by Hackermanlmao** [comment]
> Try to disable privnote sniper. Sometimes it makes the program crash.

I fixed it, I was just being dumb
