### ISSUE TITLE
You are being rate limited

### ISSUE THREAD

**Issue by ursnipr** [Vedza/NitroSniperGo#185]
Hey i have been getting a message while snipping nitros
![image](https://user-images.githubusercontent.com/79354635/108588389-f21d1d80-737e-11eb-9432-e407ac6b79d4.png)

**Comment by Vedza** [comment]
https://github.com/Vedza/NitroSniperGo/issues?q=is%3Aissue+is%3Aclosed+rate+limited

**Comment by ursnipr** [comment]
but does it snipe and apply code if a real nitro is dropped?

**Comment by Vedza** [comment]
Probably not

**Comment by ursnipr** [comment]
so any fix?

**Comment by Vedza** [comment]
It comes from discord, I can't do anything. Maybe you have too many alts, but I can't help you more than that

**Comment by ursnipr** [comment]
i have only 1 alt
