### ISSUE TITLE
Thank You :D This Works

### ISSUE THREAD

**Issue by 9lag** [Vedza/NitroSniperGo#188]
![Screenshot 2021-02-22 at 7 25 21 AM](https://user-images.githubusercontent.com/78369995/108738900-b22e7580-74f9-11eb-8266-c07e7eac3db0.png)
![Screenshot 2021-02-22 at 6 53 04 AM](https://user-images.githubusercontent.com/78369995/108738927-b78bc000-74f9-11eb-9aef-fded7b2a8b16.png)
Thanks too you i have sniped 6 months of nitro This works people
The first one is my main and the second one is my alt

**Comment by Vedza** [comment]
Hi !
I'm glad you got free Nitro.
We should use this issue to show that the sniper works, here is my personal account.

![image](https://user-images.githubusercontent.com/28839427/108739463-f68b3700-7534-11eb-99a6-14c5402728a4.png)

**Comment by 9lag** [comment]
YEssirrrrrrrrrr

**Comment by FokshaWasTaken** [comment]
yeah, disclaimer to stop when you think thats enough lol or your gonna get termed

**Comment by Vedza** [comment]
yeah be careful, I only claim 2 Nitro by month

**Comment by 9lag** [comment]
> yeah be careful, I only claim 2 Nitro by month



> yeah, disclaimer to stop when you think thats enough lol or your gonna get termed

LOLS IM TRYING I MADE AN ALT ME AND MY FRIENDS ARE GONNA JOIN A SH*T TON OF SERVERS AND SEE WHO CAN SNIPE MOST CODES IN A WEEK

**Comment by 9lag** [comment]
> Hi !
> I'm glad you got free Nitro.
> We should use this issue to show that the sniper works, here is my personal account.
> 
> ![image](https://user-images.githubusercontent.com/28839427/108739463-f68b3700-7534-11eb-99a6-14c5402728a4.png)

DAng thats really nice

**Comment by NotSwaraj** [comment]
Dang that's nice but I'm too scared to get my account banned :/

**Comment by 9lag** [comment]
> Dang that's nice but I'm too scared to get my account banned :/

You wont just after 3 snipes use another account
