### ISSUE TITLE
Unknows issue :/

### ISSUE THREAD

**Issue by kelukelol** [Vedza/NitroSniperGo#193]
**Describe the bug**
[DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string
 
**Screenshots**
 
![image](https://user-images.githubusercontent.com/76735490/108994903-09247e00-76a5-11eb-8c43-31bc5c1f23f2.png)

**Comment by Vedza** [comment]
This is literally the first issue in Known Issues

**Comment by dweee** [comment]
Might be worth it to add to the template or on startup for the bot so braindead monkeys don't open issues for this.

**Comment by Vedza** [comment]
The first line of the template tells to check previous issues but I'll add a link to know issues
