### ISSUE TITLE
Error with opening

### ISSUE THREAD

**Issue by Weirdx** [Vedza/NitroSniperGo#194]
i install everthing and i have 10:01:09 [x] Failed read file: open settings.json: The specified file could not be found.
exit status 4294967295

**Comment by 9lag** [comment]
what are you hosting on

**Comment by Weirdx** [comment]
cmd box / pc

**Comment by Weirdx** [comment]
ahh and also i use go 1.6

**Comment by PeterStrick** [comment]
> i install everthing and i have 10:01:09 [x] Failed read file: open settings.json: The specified file could not be found.
> exit status 4294967295

Have you made sure that the file settings.json exists in the same Directory as the Nitro Sniper itself?

**Comment by Weirdx** [comment]
Yes.

**Comment by PeterStrick** [comment]
> Yes.

So are you using the already made Nitro Sniper Go File from the [Releases Page](https://github.com/Vedza/NitroSniperGo/releases/tag/v3.0), or are you just running sniper.go?

**Comment by Weirdx** [comment]
Idk how but sniper exe work but go sniper don't

**Comment by PeterStrick** [comment]
> Idk how but sniper exe work but go sniper don't

If the Exe File works, then please use that ok?

**Comment by Weirdx** [comment]
https://prnt.sc/106hlt0 "can't find file"

**Comment by Weirdx** [comment]
ok

**Comment by PeterStrick** [comment]
So, does the EXE file work? If it does, then you can close this Issue,

**Comment by NotSwaraj** [comment]
open the cmd THAN type NitroSniperGo.exe
