### ISSUE TITLE
Process wont begin

### ISSUE THREAD

**Issue by snipefn** [Vedza/NitroSniperGo#195]
The program says "sniper is ready" and does nothing. LEft it on overnight and it didn't move

![Screenshot 2021-02-24 105101](https://user-images.githubusercontent.com/79592341/109026994-5517f880-768e-11eb-8f26-8b0b9819e976.png)

**Comment by snipefn** [comment]
i joined another 20 servers and let it run again and it still does nthng

**Comment by Vedza** [comment]
Send `https://discord.gift/Npzm2WXKAzcs7fgn` somewhere on discord and see if it does something

**Comment by snipefn** [comment]
It did, you're right. Are there any servers you recommend joining? Im in like 60 rn

**Comment by Vedza** [comment]
I don't
