### ISSUE TITLE
Sniper Giving Error in Heroku.

### ISSUE THREAD

**Issue by Bandito111** [Vedza/NitroSniperGo#196]
"at=error code=H14 desc="No web processes running" method=GET path="/" host=snooper1234.herokuapp.com request_id=2479360e-63da-417e-9c71-afe3af99b709 fwd="X.X.X.X" dyno= connect= service= status=503 bytes= protocol=https"

I got this error in logs when I try to open the app on heroku and before this I was shown that the quota limit has been exceeded/finished, I made a new account on heroku, changed my token and put a new one. Still the problem persists.

**Comment by Weirdx** [comment]
LOL YOU IDIOT THX FOR IP 5.62.35.136

**Comment by Weirdx** [comment]
https://prnt.sc/106bx97

**Comment by DarkGD123** [comment]
Bruh

**Comment by Weirdx** [comment]
bro i still have ip...

**Comment by Weirdx** [comment]
oh and i see pass to your account to heroku app encrypted

**Comment by Vedza** [comment]
You don't need to click on open App, just follow the Readme and go to logs.

And about his IP, you won't do anything with it, and please stop posting dumb stuff.

**Comment by Bandito111** [comment]
> You don't need to click on open App, just follow the Readme and go to logs.
> 
> And about his IP, you won't do anything with it, and please stop posting dumb stuff.

I deleted the account associated with that app and the app a long time ago, let them try. Also the logs show the same error again and again it wont go away.

**Comment by Weirdx** [comment]
.-. no one help me

**Comment by Bandito111** [comment]
> .-. no one help me
What help do you need?
