### ISSUE TITLE
Can I run on a termux?

### ISSUE THREAD

**Issue by Sunrise-dc** [Vedza/NitroSniperGo#201]
How to run Nitrosnipergo on termux?

**Comment by Vedza** [comment]
You need to install golang and git on termux.
Then git clone `https://github.com/Vedza/NitroSniperGo` and follow steps in the Readme to compile.
But if you want free 24/7 you should use Heroku, it's really easy to set up.

**Comment by Sunrise-dc** [comment]
Which directory should you run? `cd...`

**Comment by Vedza** [comment]
`https://github.com/Vedza/NitroSniperGo && cd NitroSniperGo`

**Comment by Sunrise-dc** [comment]
`~/NitroSniperGo $ python NitroSniperGo.py
python: can't open file '/data/data/com.termux/files/home/NitroSniperGo/NitroSniperGo.py': [Errno 2] No such file or directory`

**Comment by Vedza** [comment]
It's not python
https://github.com/Vedza/NitroSniperGo#usage
You should definitely try Heroku
