### ISSUE TITLE
(Suggestion)Snipe classic for one account and snipe nitro for another

### ISSUE THREAD

**Issue by ibndiaye** [Vedza/NitroSniperGo#202]
Hello Vedza, what I mean by this is that all sniped nitro classic codes goes to one account, and all nitro codes go to another account.
It would be useful if you have multiple accounts
Not sure if this is possible but would definitely be a cool feature

**Comment by Vedza** [comment]
Hi,
I don't think that it's possible as I only know if it's a classic or not after redeeming it. Maybe I could check before, but it will take too much time.
