### ISSUE TITLE
error on repl.it

### ISSUE THREAD

**Issue by HydraX4** [Vedza/NitroSniperGo#205]
hi, i created the .replit file. and when i click run i get error: "can't load package: package .: no Go files in /home/runner"
on repl.it it i have hacker plan so it will be hosted 24/7

**Comment by HydraX4** [comment]
i also did wget (link to linux release) and unzipped it.

**Comment by Vedza** [comment]
I don't use repl.it so I have no idea sry. But you don't have to create the .replit file as I have already created it
Btw I still don't understand why people don't want to use heroku which is free and so easy to set up.

**Comment by HydraX4** [comment]
I seemed to fix it! how can i enable auto server joiner?

**Comment by Vedza** [comment]
https://github.com/Vedza/NitroSniperGo#usage
