### ISSUE TITLE
Auto Server Joiner not working on heroku?

### ISSUE THREAD

**Issue by HydraX4** [Vedza/NitroSniperGo#207]
hello, thanks for responding, I am now hosting it on Heroku with the credit card added for the free 1000 dyno hours :P. 

But When i run it (Alt and main go on dnd mode) my alt doesnt join any servers. here is my config:

  },
  "invite": {
    "enable": true,
    "delay": {
      "min": 1,
      "max": 1
    },
    "max": 99,
    "cooldown": 2
  },

**Comment by Vedza** [comment]
Stop opening new issue and comment on your previous one.
