### ISSUE TITLE
discord account deleted D:

### ISSUE THREAD

**Issue by JarnoXYZ** [Vedza/NitroSniperGo#210]
So i claimed 1 nitro classic, was calling with a friend... and then... logged out. Tried to log back in ''This account has been disabled''. D: Does anyone know how to get it re enabled?

**Comment by DarkGD123** [comment]
This isnt a bug by the way

Possible cause:

•Getting nitro a lot
•Self Bot

Only way to fix it is just go make a request in discord

dis.gd/support/, then select trust and safety (then do your thing)

**Comment by JarnoXYZ** [comment]
i got 1 nitro and didn't use any self bot. I emailed them and they say they cant re activate it but i sent another one. Hopefully they active it again

**Comment by JarnoXYZ** [comment]
maybe im just really bad at writing emails

**Comment by Elixirrr** [comment]
Damn, I had this running on a vps for 2 days and still haven't snipped anything and also got terminated.

**Comment by DarkGD123** [comment]
I (mostly) avoid the termination by disabling some useless stuff in `setting.json` and i only set the max nitro to 1 and the cooldown is 48h or more
