### ISSUE TITLE
Error in termux

### ISSUE THREAD

**Issue by Sunrise-dc** [Vedza/NitroSniperGo#212]
Hi, I'm sorry to contact you again for a stupid reason.  Last time and this time I got an error in Termux after copying that there are no files in the NitroSniperGo directory.  (also, in the regular version, NitroSniper gives another error) can you tell me what the problem is?  And one more thing ... can you tell us about Heroku, as I understand it is hosting, but how to start and work in it?

(Screenshot links) 
https://drive.google.com/folderview?id=1aXC_oqoQxHBMeFd0BxmrqhdO21k0W-nE

**Comment by Vedza** [comment]
On the first screenshot, you put a bad token.
And as I told you for Heroku, it's free 24/7 host.
Just create an account.
- [Deploy on Heroku](https://heroku.com/deploy?template=https://github.com/Vedza/NitroSniperGo/tree/heroku) (Free 24/7)
   * Edit settings
   * Deploy
   * Resources -> enable sniper
   * See logs in More -> View logs

**Comment by atz-dev** [comment]
Hello @Sunrise-dc,  
As you can see below, the binary isn't NitroSniperGo or NitroSniperGo.py, like in your second screenshot.  
The reason it's simple : you're using the Go version of the script. Not Python.  
All the necessaries informations are available in the README (cf: Compile it yourself), or you can just take the release.  

<img width="271" alt="tree" src="https://user-images.githubusercontent.com/44492274/110511876-fed29d00-8104-11eb-857e-765179a97f88.png">

**Comment by Sunrise-dc** [comment]
Insert token here? (Screenshot) 

https://drive.google.com/folderview?id=1aXC_oqoQxHBMeFd0BxmrqhdO21k0W-nE

**Comment by Vedza** [comment]
Yes
https://github.com/Vedza/NitroSniperGo#usage

**Comment by Sunrise-dc** [comment]
Im sorry, but..is that's all?

[](https://drive.google.com/folderview?id=1aXC_oqoQxHBMeFd0BxmrqhdO21k0W-nE)

**Comment by Sunrise-dc** [comment]
Where is "Resources - Enable snipper"?

**Comment by Vedza** [comment]
Just look on your second screen, resources tab is here

**Comment by Sunrise-dc** [comment]
Okay, I hit that switch, what's next?

![IMG_20210309_204205.jpg](https://user-images.githubusercontent.com/67816756/110521040-f0da4780-8117-11eb-8dc9-896a37efc266.jpg)

**Comment by Vedza** [comment]
Why the hell can't you just read the readme like everybody does ?
It's working now, you can see the logs 

> See logs in More -> View logs

**Comment by Sunrise-dc** [comment]
> Why the hell can't you just read the readme like everybody does ?
> It's working now, you can see the logs 
> 
Thank you ... sorry for wasting your time on this.  It's just that I'm not perfect in English and, although ± I understand cmd, I first heard about Heroku and did not understand where and what to do
