### ISSUE TITLE
Nitro Sniper bug Heroku

### ISSUE THREAD

**Issue by inverspe** [Vedza/NitroSniperGo#214]
So when I view the logs on Heroku nitro sniper sometimes it gives me this:

2021/03/10 11:08:47 [DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string
2021-03-10T11:08:48.418615+00:00 app[sniper.1]: 2021/03/10 11:08:48 [DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string

But it still continues to function the giveaway sniper and the nitro sniper still works is that an issue/bug or its normal?

**Comment by FeelsBadMan1** [comment]
> So when I view the logs on Heroku nitro sniper sometimes it gives me this:
> 
> 2021/03/10 11:08:47 [DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string
> 2021-03-10T11:08:48.418615+00:00 app[sniper.1]: 2021/03/10 11:08:48 [DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string
> 
> But it still continues to function the giveaway sniper and the nitro sniper still works is that an issue/bug or its normal?

This is not a error. You really should read the Nitrodescription carefully then you would have understood it.
![image](https://user-images.githubusercontent.com/40109798/111605212-66a87800-87d6-11eb-9aa2-cf704e621f54.png)
