### ISSUE TITLE
Nitro giveaway sniper

### ISSUE THREAD

**Issue by inverspe** [Vedza/NitroSniperGo#215]
What if you manually join a giveaway but the nitro sniper/giveaway sniper is not running yet after that you run the nitro sniper/giveaway sniper then after you win the giveaway that you manually joined does it still messages the host or not?

**Comment by Vedza** [comment]
Yes it will still work.
Please don't put "bug" label on issues that are absolutely not bug, neither issue actually in that case

**Comment by inverspe** [comment]
> Yes it will still work.
> Please don't put "bug" label on issues that are absolutely not bug, neither issue actually in that case

Im sorry Im new to github I do not know how to remove labels Im very sorry

**Comment by Vedza** [comment]
np
