### ISSUE TITLE
Error while starting Sniper

### ISSUE THREAD

**Issue by FeelsBadMan1** [Vedza/NitroSniperGo#216]
Hello, i bought a Linux Debina10 server and installed go successfully however the sniper wont start somehow "Permission Error" anyone could help me with that?
![image](https://user-images.githubusercontent.com/40109798/111042655-bab20600-843e-11eb-93d1-e04c6aa63ac1.png)

**Comment by PeterStrick** [comment]
> Hello, i bought a Linux Debina10 server and installed go successfully however the sniper wont start somehow "Permission Error" anyone could help me with that?
> ![image](https://user-images.githubusercontent.com/40109798/111042655-bab20600-843e-11eb-93d1-e04c6aa63ac1.png)

Maybe mark the sniper file as executable by entering  `chmod +x ./NitroSniperGo` ? 
Also make sure that you typed it in correctly, by listing files with `ls`
