### ISSUE TITLE
NitrosniperGo Error

### ISSUE THREAD

**Issue by FeelsBadMan1** [Vedza/NitroSniperGo#218]
Hello, i bought myself a linuxserver and did run it. At fist i thought its working with no issures. Sniper started usually and all seems to be wroking. However after some time i noticed that the Process where stopped after i closed mobaxterm so i asked others. They told me i should use screen to start things so they keep running so i did run following command: screen-S Nitrosniper ./NitroSniperGo

The bot where started with screen sucessfully however i let it run over night and at the Morning as i looked it somehow closed the Sniper. Could anyone help me please?

**Comment by Vedza** [comment]
Run it with `nohup ./NistroSniperGo &` or add ` > logs.txt` add the end of your command you will have a nohup.out (or logs.txt if you choose the other option) with all the logs and we'll be able to see what's the problem.

And please stop putting bug label for stuff related to you or if you don't know if it's a bug or not yet.

**Comment by FeelsBadMan1** [comment]
Nice thats for the Information. the output of the logsfile is following:

```
[H[2J[3J
â–“â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–„  â–ˆâ–ˆâ–“  â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ  â–„â–ˆâ–ˆâ–ˆâ–ˆâ–„   â–’â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ   â–ˆâ–ˆâ–€â–ˆâ–ˆâ–ˆ  â–“â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–„      â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ  â–ˆâ–ˆâ–ˆâ–„    â–ˆ  â–ˆâ–ˆâ–“ â–ˆâ–ˆâ–“â–ˆâ–ˆâ–ˆ  â–“â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ  â–ˆâ–ˆâ–€â–ˆâ–ˆâ–ˆ
â–’â–ˆâ–ˆâ–€ â–ˆâ–ˆâ–Œâ–“â–ˆâ–ˆâ–’â–’â–ˆâ–ˆ    â–’ â–’â–ˆâ–ˆâ–€ â–€â–ˆ  â–’â–ˆâ–ˆâ–’  â–ˆâ–ˆâ–’â–“â–ˆâ–ˆ â–’ â–ˆâ–ˆâ–’â–’â–ˆâ–ˆâ–€ â–ˆâ–ˆâ–Œ   â–’â–ˆâ–ˆ    â–’  â–ˆâ–ˆ â–€â–ˆ   â–ˆ â–“â–ˆâ–ˆâ–’â–“â–ˆâ–ˆâ–‘  â–ˆâ–ˆâ–’â–“â–ˆ   â–€ â–“â–ˆâ–ˆ â–’ â–ˆâ–ˆâ–’
â–‘â–ˆâ–ˆ   â–ˆâ–Œâ–’â–ˆâ–ˆâ–’â–‘ â–“â–ˆâ–ˆâ–„   â–’â–“â–ˆ    â–„ â–’â–ˆâ–ˆâ–‘  â–ˆâ–ˆâ–’â–“â–ˆâ–ˆ â–‘â–„â–ˆ â–’â–‘â–ˆâ–ˆ   â–ˆâ–Œ   â–‘ â–“â–ˆâ–ˆâ–„   â–“â–ˆâ–ˆ  â–€â–ˆ â–ˆâ–ˆâ–’â–’â–ˆâ–ˆâ–’â–“â–ˆâ–ˆâ–‘ â–ˆâ–ˆâ–“â–’â–’â–ˆâ–ˆâ–ˆ   â–“â–ˆâ–ˆ â–‘â–„â–ˆ â–’
â–‘â–“â–ˆâ–„   â–Œâ–‘â–ˆâ–ˆâ–‘  â–’   â–ˆâ–ˆâ–’â–’â–“â–“â–„ â–„â–ˆâ–ˆâ–’â–’â–ˆâ–ˆ   â–ˆâ–ˆâ–‘â–’â–ˆâ–ˆâ–€â–€â–ˆâ–„  â–‘â–“â–ˆâ–„   â–Œ     â–’   â–ˆâ–ˆâ–’â–“â–ˆâ–ˆâ–’  â–â–Œâ–ˆâ–ˆâ–’â–‘â–ˆâ–ˆâ–‘â–’â–ˆâ–ˆâ–„â–ˆâ–“â–’ â–’â–’â–“â–ˆ  â–„ â–’â–ˆâ–ˆâ–€â–€â–ˆâ–„
â–‘â–’â–ˆâ–ˆâ–ˆâ–ˆâ–“ â–‘â–ˆâ–ˆâ–‘â–’â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–’â–’â–’ â–“â–ˆâ–ˆâ–ˆâ–€ â–‘â–‘ â–ˆâ–ˆâ–ˆâ–ˆâ–“â–’â–‘â–‘â–ˆâ–ˆâ–“ â–’â–ˆâ–ˆâ–’â–‘â–’â–ˆâ–ˆâ–ˆâ–ˆâ–“    â–’â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–’â–’â–’â–ˆâ–ˆâ–‘   â–“â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ–‘â–’â–ˆâ–ˆâ–’ â–‘  â–‘â–‘â–’â–ˆâ–ˆâ–ˆâ–ˆâ–’â–‘â–ˆâ–ˆâ–“ â–’â–ˆâ–ˆâ–’
â–’â–’â–“  â–’ â–‘â–“  â–’ â–’â–“â–’ â–’ â–‘â–‘ â–‘â–’ â–’  â–‘â–‘ â–’â–‘â–’â–‘â–’â–‘ â–‘ â–’â–“ â–‘â–’â–“â–‘ â–’â–’â–“  â–’    â–’ â–’â–“â–’ â–’ â–‘â–‘ â–’â–‘   â–’ â–’ â–‘â–“  â–’â–“â–’â–‘ â–‘  â–‘â–‘â–‘ â–’â–‘ â–‘â–‘ â–’â–“ â–‘â–’â–“â–‘
â–‘ â–’  â–’  â–’ â–‘â–‘ â–‘â–’  â–‘ â–‘  â–‘  â–’     â–‘ â–’ â–’â–‘   â–‘â–’ â–‘ â–’â–‘ â–‘ â–’  â–’    â–‘ â–‘â–’  â–‘ â–‘â–‘ â–‘â–‘   â–‘ â–’â–‘ â–’ â–‘â–‘â–’ â–‘      â–‘ â–‘  â–‘  â–‘â–’ â–‘ â–’â–‘
â–‘ â–‘  â–‘  â–’ â–‘â–‘  â–‘  â–‘  â–‘        â–‘ â–‘ â–‘ â–’    â–‘â–‘   â–‘  â–‘ â–‘  â–‘    â–‘  â–‘  â–‘     â–‘   â–‘ â–‘  â–’ â–‘â–‘â–‘          â–‘     â–‘â–‘   â–‘
â–‘     â–‘        â–‘  â–‘ â–‘          â–‘ â–‘     â–‘        â–‘             â–‘           â–‘  â–‘              â–‘  â–‘   â–‘
â–‘                   â–‘                           â–‘
	
2021/03/15 17:16:09 [DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string
2021/03/15 17:16:10 [DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string
Sniping Discord Nitro, Giveaway and Privnote for The German Destroyer on 214 servers and 4 accounts ðŸ”«

17:16:11 [+] Sniper is ready
[H[2J[3J
â–“â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–„  â–ˆâ–ˆâ–“  â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ  â–„â–ˆâ–ˆâ–ˆâ–ˆâ–„   â–’â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ   â–ˆâ–ˆâ–€â–ˆâ–ˆâ–ˆ  â–“â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–„      â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ  â–ˆâ–ˆâ–ˆâ–„    â–ˆ  â–ˆâ–ˆâ–“ â–ˆâ–ˆâ–“â–ˆâ–ˆâ–ˆ  â–“â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ  â–ˆâ–ˆâ–€â–ˆâ–ˆâ–ˆ
â–’â–ˆâ–ˆâ–€ â–ˆâ–ˆâ–Œâ–“â–ˆâ–ˆâ–’â–’â–ˆâ–ˆ    â–’ â–’â–ˆâ–ˆâ–€ â–€â–ˆ  â–’â–ˆâ–ˆâ–’  â–ˆâ–ˆâ–’â–“â–ˆâ–ˆ â–’ â–ˆâ–ˆâ–’â–’â–ˆâ–ˆâ–€ â–ˆâ–ˆâ–Œ   â–’â–ˆâ–ˆ    â–’  â–ˆâ–ˆ â–€â–ˆ   â–ˆ â–“â–ˆâ–ˆâ–’â–“â–ˆâ–ˆâ–‘  â–ˆâ–ˆâ–’â–“â–ˆ   â–€ â–“â–ˆâ–ˆ â–’ â–ˆâ–ˆâ–’
â–‘â–ˆâ–ˆ   â–ˆâ–Œâ–’â–ˆâ–ˆâ–’â–‘ â–“â–ˆâ–ˆâ–„   â–’â–“â–ˆ    â–„ â–’â–ˆâ–ˆâ–‘  â–ˆâ–ˆâ–’â–“â–ˆâ–ˆ â–‘â–„â–ˆ â–’â–‘â–ˆâ–ˆ   â–ˆâ–Œ   â–‘ â–“â–ˆâ–ˆâ–„   â–“â–ˆâ–ˆ  â–€â–ˆ â–ˆâ–ˆâ–’â–’â–ˆâ–ˆâ–’â–“â–ˆâ–ˆâ–‘ â–ˆâ–ˆâ–“â–’â–’â–ˆâ–ˆâ–ˆ   â–“â–ˆâ–ˆ â–‘â–„â–ˆ â–’
â–‘â–“â–ˆâ–„   â–Œâ–‘â–ˆâ–ˆâ–‘  â–’   â–ˆâ–ˆâ–’â–’â–“â–“â–„ â–„â–ˆâ–ˆâ–’â–’â–ˆâ–ˆ   â–ˆâ–ˆâ–‘â–’â–ˆâ–ˆâ–€â–€â–ˆâ–„  â–‘â–“â–ˆâ–„   â–Œ     â–’   â–ˆâ–ˆâ–’â–“â–ˆâ–ˆâ–’  â–â–Œâ–ˆâ–ˆâ–’â–‘â–ˆâ–ˆâ–‘â–’â–ˆâ–ˆâ–„â–ˆâ–“â–’ â–’â–’â–“â–ˆ  â–„ â–’â–ˆâ–ˆâ–€â–€â–ˆâ–„
â–‘â–’â–ˆâ–ˆâ–ˆâ–ˆâ–“ â–‘â–ˆâ–ˆâ–‘â–’â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–’â–’â–’ â–“â–ˆâ–ˆâ–ˆâ–€ â–‘â–‘ â–ˆâ–ˆâ–ˆâ–ˆâ–“â–’â–‘â–‘â–ˆâ–ˆâ–“ â–’â–ˆâ–ˆâ–’â–‘â–’â–ˆâ–ˆâ–ˆâ–ˆâ–“    â–’â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–’â–’â–’â–ˆâ–ˆâ–‘   â–“â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ–‘â–’â–ˆâ–ˆâ–’ â–‘  â–‘â–‘â–’â–ˆâ–ˆâ–ˆâ–ˆâ–’â–‘â–ˆâ–ˆâ–“ â–’â–ˆâ–ˆâ–’
â–’â–’â–“  â–’ â–‘â–“  â–’ â–’â–“â–’ â–’ â–‘â–‘ â–‘â–’ â–’  â–‘â–‘ â–’â–‘â–’â–‘â–’â–‘ â–‘ â–’â–“ â–‘â–’â–“â–‘ â–’â–’â–“  â–’    â–’ â–’â–“â–’ â–’ â–‘â–‘ â–’â–‘   â–’ â–’ â–‘â–“  â–’â–“â–’â–‘ â–‘  â–‘â–‘â–‘ â–’â–‘ â–‘â–‘ â–’â–“ â–‘â–’â–“â–‘
â–‘ â–’  â–’  â–’ â–‘â–‘ â–‘â–’  â–‘ â–‘  â–‘  â–’     â–‘ â–’ â–’â–‘   â–‘â–’ â–‘ â–’â–‘ â–‘ â–’  â–’    â–‘ â–‘â–’  â–‘ â–‘â–‘ â–‘â–‘   â–‘ â–’â–‘ â–’ â–‘â–‘â–’ â–‘      â–‘ â–‘  â–‘  â–‘â–’ â–‘ â–’â–‘
â–‘ â–‘  â–‘  â–’ â–‘â–‘  â–‘  â–‘  â–‘        â–‘ â–‘ â–‘ â–’    â–‘â–‘   â–‘  â–‘ â–‘  â–‘    â–‘  â–‘  â–‘     â–‘   â–‘ â–‘  â–’ â–‘â–‘â–‘          â–‘     â–‘â–‘   â–‘
â–‘     â–‘        â–‘  â–‘ â–‘          â–‘ â–‘     â–‘        â–‘             â–‘           â–‘  â–‘              â–‘  â–‘   â–‘
â–‘                   â–‘                           â–‘
	
2021/03/15 17:17:48 [DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string
2021/03/15 17:17:49 [DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string
Sniping Discord Nitro, Giveaway and Privnote for The German Destroyer on 214 servers and 4 accounts ðŸ”«

17:17:50 [+] Sniper is ready
```

**Comment by Vedza** [comment]
it's working rn

**Comment by FeelsBadMan1** [comment]
no only one instance is running. and the Sniper worked before too but my issure where that with the screencommand iit stopped the sniper after some time.

**Comment by Vedza** [comment]
I know, that's why I asked you to save the logs so if it happens again we'll see exactly what happened

**Comment by FeelsBadMan1** [comment]
Okey. Now i closed the screen instance and used the nohup command again. i now have a simillar output. Do you know if the logs becoming updated on new things or it is just saving once i type the command? and is the sniper now started or not?
```
[H[2J[3J
â–“â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–„  â–ˆâ–ˆâ–“  â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ  â–„â–ˆâ–ˆâ–ˆâ–ˆâ–„   â–’â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ   â–ˆâ–ˆâ–€â–ˆâ–ˆâ–ˆ  â–“â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–„      â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ  â–ˆâ–ˆâ–ˆâ–„    â–ˆ  â–ˆâ–ˆâ–“ â–ˆâ–ˆâ–“â–ˆâ–ˆâ–ˆ  â–“â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ  â–ˆâ–ˆâ–€â–ˆâ–ˆâ–ˆ
â–’â–ˆâ–ˆâ–€ â–ˆâ–ˆâ–Œâ–“â–ˆâ–ˆâ–’â–’â–ˆâ–ˆ    â–’ â–’â–ˆâ–ˆâ–€ â–€â–ˆ  â–’â–ˆâ–ˆâ–’  â–ˆâ–ˆâ–’â–“â–ˆâ–ˆ â–’ â–ˆâ–ˆâ–’â–’â–ˆâ–ˆâ–€ â–ˆâ–ˆâ–Œ   â–’â–ˆâ–ˆ    â–’  â–ˆâ–ˆ â–€â–ˆ   â–ˆ â–“â–ˆâ–ˆâ–’â–“â–ˆâ–ˆâ–‘  â–ˆâ–ˆâ–’â–“â–ˆ   â–€ â–“â–ˆâ–ˆ â–’ â–ˆâ–ˆâ–’
â–‘â–ˆâ–ˆ   â–ˆâ–Œâ–’â–ˆâ–ˆâ–’â–‘ â–“â–ˆâ–ˆâ–„   â–’â–“â–ˆ    â–„ â–’â–ˆâ–ˆâ–‘  â–ˆâ–ˆâ–’â–“â–ˆâ–ˆ â–‘â–„â–ˆ â–’â–‘â–ˆâ–ˆ   â–ˆâ–Œ   â–‘ â–“â–ˆâ–ˆâ–„   â–“â–ˆâ–ˆ  â–€â–ˆ â–ˆâ–ˆâ–’â–’â–ˆâ–ˆâ–’â–“â–ˆâ–ˆâ–‘ â–ˆâ–ˆâ–“â–’â–’â–ˆâ–ˆâ–ˆ   â–“â–ˆâ–ˆ â–‘â–„â–ˆ â–’
â–‘â–“â–ˆâ–„   â–Œâ–‘â–ˆâ–ˆâ–‘  â–’   â–ˆâ–ˆâ–’â–’â–“â–“â–„ â–„â–ˆâ–ˆâ–’â–’â–ˆâ–ˆ   â–ˆâ–ˆâ–‘â–’â–ˆâ–ˆâ–€â–€â–ˆâ–„  â–‘â–“â–ˆâ–„   â–Œ     â–’   â–ˆâ–ˆâ–’â–“â–ˆâ–ˆâ–’  â–â–Œâ–ˆâ–ˆâ–’â–‘â–ˆâ–ˆâ–‘â–’â–ˆâ–ˆâ–„â–ˆâ–“â–’ â–’â–’â–“â–ˆ  â–„ â–’â–ˆâ–ˆâ–€â–€â–ˆâ–„
â–‘â–’â–ˆâ–ˆâ–ˆâ–ˆâ–“ â–‘â–ˆâ–ˆâ–‘â–’â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–’â–’â–’ â–“â–ˆâ–ˆâ–ˆâ–€ â–‘â–‘ â–ˆâ–ˆâ–ˆâ–ˆâ–“â–’â–‘â–‘â–ˆâ–ˆâ–“ â–’â–ˆâ–ˆâ–’â–‘â–’â–ˆâ–ˆâ–ˆâ–ˆâ–“    â–’â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–’â–’â–’â–ˆâ–ˆâ–‘   â–“â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ–‘â–’â–ˆâ–ˆâ–’ â–‘  â–‘â–‘â–’â–ˆâ–ˆâ–ˆâ–ˆâ–’â–‘â–ˆâ–ˆâ–“ â–’â–ˆâ–ˆâ–’
â–’â–’â–“  â–’ â–‘â–“  â–’ â–’â–“â–’ â–’ â–‘â–‘ â–‘â–’ â–’  â–‘â–‘ â–’â–‘â–’â–‘â–’â–‘ â–‘ â–’â–“ â–‘â–’â–“â–‘ â–’â–’â–“  â–’    â–’ â–’â–“â–’ â–’ â–‘â–‘ â–’â–‘   â–’ â–’ â–‘â–“  â–’â–“â–’â–‘ â–‘  â–‘â–‘â–‘ â–’â–‘ â–‘â–‘ â–’â–“ â–‘â–’â–“â–‘
â–‘ â–’  â–’  â–’ â–‘â–‘ â–‘â–’  â–‘ â–‘  â–‘  â–’     â–‘ â–’ â–’â–‘   â–‘â–’ â–‘ â–’â–‘ â–‘ â–’  â–’    â–‘ â–‘â–’  â–‘ â–‘â–‘ â–‘â–‘   â–‘ â–’â–‘ â–’ â–‘â–‘â–’ â–‘      â–‘ â–‘  â–‘  â–‘â–’ â–‘ â–’â–‘
â–‘ â–‘  â–‘  â–’ â–‘â–‘  â–‘  â–‘  â–‘        â–‘ â–‘ â–‘ â–’    â–‘â–‘   â–‘  â–‘ â–‘  â–‘    â–‘  â–‘  â–‘     â–‘   â–‘ â–‘  â–’ â–‘â–‘â–‘          â–‘     â–‘â–‘   â–‘
â–‘     â–‘        â–‘  â–‘ â–‘          â–‘ â–‘     â–‘        â–‘             â–‘           â–‘  â–‘              â–‘  â–‘   â–‘
â–‘                   â–‘                           â–‘
	
2021/03/15 17:31:31 [DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string
2021/03/15 17:31:31 [DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string
2021/03/15 17:31:31 [DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string
2021/03/15 17:31:32 [DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string
Sniping Discord Nitro, Giveaway and Privnote for The German Destroyer on 214 servers and 4 accounts ðŸ”«
```

**Comment by Vedza** [comment]
Yeah it's running, the file will be updated, just `cat nohup.out` to see updated

**Comment by FeelsBadMan1** [comment]
oh okey thaks. I will write later if there is any new log that seems to be a error / if it terminate the process randomly

**Comment by Vedza** [comment]
There is a bug with privnote sniper that make it crashed, it's already in the know issues and the only bug that makes it crash
I suggest you to disable it in the settings.

**Comment by FeelsBadMan1** [comment]
Oh okey thanks for the info & btw do you know how i stop the sniper if its started with nohup so its not running twice if i start it again?

**Comment by Vedza** [comment]
Find the PID with `ps -aux | grep NitroSniperGo` then `kill <PID>`

**Comment by FeelsBadMan1** [comment]
Okey thanks for the Info!

**Comment by FeelsBadMan1** [comment]
Is this usual? It shows me a running process but i cant stop it because the ID Changing each time so if i put kill <ID> its not working because the ID alredy changed

![image](https://user-images.githubusercontent.com/40109798/111214576-60e24500-85d2-11eb-99cb-a40efe0b0b81.png)

**Comment by Vedza** [comment]
It's the process of the command itself, so it's normal

**Comment by FeelsBadMan1** [comment]
oh okey thanks for your help!

**Comment by FeelsBadMan1** [comment]
also a support for mor ebots would be nice, There are a large amount of giveaway bots out there that also use the same reaction so it not should be hard to add BotIDs to a list i think Im not good in GO (never looked at go code) but i wrote a Sniper in Python alredy that had multiplie botsupport. however Python is a slow language so the Sniper is not rly fast. Thats why i looked for a Sniper written in GO.
Somehow the Sniper is still slow for me. its mostly sniping in about 200 ms.

**Comment by iiTrauma** [comment]
> also a support for mor ebots would be nice, There are a large amount of giveaway bots out there that also use the same reaction so it not should be hard to add BotIDs to a list i think Im not good in GO (never looked at go code) but i wrote a Sniper in Python alredy that had multiplie botsupport. however Python is a slow language so the Sniper is not rly fast. Thats why i looked for a Sniper written in GO.
> Somehow the Sniper is still slow for me. its mostly sniping in about 200 ms.

heroku gives me 50 - 20ms when sniping
i think you should get a better location on your vps

**Comment by DarkGD123** [comment]
> > also a support for mor ebots would be nice, There are a large amount of giveaway bots out there that also use the same reaction so it not should be hard to add BotIDs to a list i think Im not good in GO (never looked at go code) but i wrote a Sniper in Python alredy that had multiplie botsupport. however Python is a slow language so the Sniper is not rly fast. Thats why i looked for a Sniper written in GO.
> > Somehow the Sniper is still slow for me. its mostly sniping in about 200 ms.
> 
> heroku gives me 50 - 20ms when sniping
> i think you should get a better location on your vps

bruh how u get 50 - 20ms, what region did you put your app

**Comment by FeelsBadMan1** [comment]
I using a german hostingservice (zaphosting) and now im running it on heroku. seems to be working there

**Comment by FeelsBadMan1** [comment]
Hey, I will close this again soon but somehow on heroku it snipes between 100ms - 300ms and thats rly slow. i have choosen euroe servers and all codes it try to redeem are alredy redeemd by other snipers i think.

**Comment by Vedza** [comment]
Maybe the discord guild you're on are not hosted in EU. But delay is relevant sometimes, the sniper is fast enough to snipe nitro. Most of the time people send already redeemed code

**Comment by FeelsBadMan1** [comment]
![image](https://user-images.githubusercontent.com/40109798/111335266-8a53ad00-8674-11eb-8c3d-8577bacbd9c3.png)

**Comment by FeelsBadMan1** [comment]
> Maybe the discord guild you're on are not hosted in EU. But delay is relevant sometimes, the sniper is fast enough to snipe nitro. Most of the time people send already redeemed code

oh okey thanks for the info

**Comment by FeelsBadMan1** [comment]
Hello, is there a alternarive to heroku? it not let me use that much tokens :joy:
![image](https://user-images.githubusercontent.com/40109798/111448067-5dec6f00-870e-11eb-9ea6-6f71aa9e187a.png)

**Comment by DarkGD123** [comment]
> Hello, is there a alternarive to heroku? it not let me use that much tokens 😂
> ![image](https://user-images.githubusercontent.com/40109798/111448067-5dec6f00-870e-11eb-9ea6-6f71aa9e187a.png)

replit.com (idk but give it a try)

**Comment by Vedza** [comment]
Repl.it isn't free.
If you don't run more than 1 dyno at the same time you should have enough credit on heroku to let it run 24/7

**Comment by DarkGD123** [comment]
oki den, also he has a lot of alts lmao, not bad

**Comment by FeelsBadMan1** [comment]
yea xd

**Comment by FeelsBadMan1** [comment]
I dont know what this error means:

11:29:14 [x] Error opening connection for mytoken, Get "https://discord.com/api/v8/gateway": http2: server sent GOAWAY and closed the connection; LastStreamID=539, ErrCode=PROTOCOL_ERROR, debug=""

**Comment by FeelsBadMan1** [comment]
> oki den, also he has a lot of alts lmao, not bad

That where heroku i not could paste all alts. i got about 700 i think

**Comment by Vedza** [comment]
Oh wtf I didn't see how many alts you have :o This is why it used too much memory. You'll be banned very fast with that

**Comment by FeelsBadMan1** [comment]
haha okey xd

**Comment by FeelsBadMan1** [comment]
yea i made these accounts with a tool but sadly heroku dont do proxysupport i think

**Comment by FeelsBadMan1** [comment]
How much alts i should maximal use?

**Comment by Vedza** [comment]
I only use 1 and I get enough Nitro

**Comment by FeelsBadMan1** [comment]
lol

**Comment by FeelsBadMan1** [comment]
![image](https://user-images.githubusercontent.com/40109798/111464191-bcbae400-8720-11eb-88b7-e221434a2c3e.png)

**Comment by FeelsBadMan1** [comment]
> I only use 1 and I get enough Nitro

on what servers are you on then? I only find servers with much users where i not know if they r legit & fake ones
