### ISSUE TITLE
Account Disabled

### ISSUE THREAD

**Issue by JarnoXYZ** [Vedza/NitroSniperGo#220]
Hello, my account got disabled for selfbots. And i have no idea what to do! Please help me.

I have tried sending an email to the support team but I only get an respond from Cylde (the bot). And i really want my account activated again. so i really really really hope someone can help me with this.
Thank you.

**Comment by Vedza** [comment]
This is not the bug and I'm sorry but you can't do aynthing about that :/

**Comment by FeelsBadMan1** [comment]
> Hello, my account got disabled for selfbots. And i have no idea what to do! Please help me.
> 
> I have tried sending an email to the support team but I only get an respond from Cylde (the bot). And i really want my account activated again. so i really really really hope someone can help me with this.
> Thank you.

I had that once too. i responsed to the bot that i want a real supporter so after some time a real one replied me but guess what. he just wrote 1 sentence by his own (Im a real supporter) and then just copypasted the text that cycle sent me before alredy. just told me that i violated the tos and they wont reinstate the account but not told me what exactly i did wrong

**Comment by PeterStrick** [comment]
> > Hello, my account got disabled for selfbots. And i have no idea what to do! Please help me.
> > I have tried sending an email to the support team but I only get an respond from Cylde (the bot). And i really want my account activated again. so i really really really hope someone can help me with this.
> > Thank you.
> 
> I had that once too. i responsed to the bot that i want a real supporter so after some time a real one replied me but guess what. he just wrote 1 sentence by his own (Im a real supporter) and then just copypasted the text that cycle sent me before alredy. just told me that i violated the tos and they wont reinstate the account but not told me what exactly i did wrong

I think you can kinda avoid your account from getting disabled, by using separate accounts and a webhook. For ex. have 3 Discord Accounts with Invite/Giveaway Sniper on, sniping Nitro and sending it to a webhook, and then your main Discord Account only Sniping from that Webhook, with the Invite and Giveaway Sniper turned off.

I'm not sure though

**Comment by Vedza** [comment]
This won't work because alts will claim codes before the main.

**Comment by Vedza** [comment]
The invite sniper is disabled for main, but not the giveaway joiner.
If you want I can add a setting to disable giveaway joiner on main, so alts will join giveaways and servers, and main will claim code from every account.
So maybe it will decrease the chance of getting banned on your main account as it will only claim code and nothing else.
