### ISSUE TITLE
How does the auto joiner work?

### ISSUE THREAD

**Issue by inverspe** [Vedza/NitroSniperGo#221]
I'm confused on how the auto joiner works I enable it, it does absolute nothing can someone tell me?

**Comment by DarkGD123** [comment]
Auto joiner:

•If someone posted a discord link in any channel of a server or in your dms, it will automatically joins you to that server (recommended but do it slowly cuz your account go phone locked if you set the delays too ***low***)

**Comment by inverspe** [comment]
> Auto joiner:
> 
> •If someone posted a discord link in any channel of a server or in your dms, it will automatically joins you to that server (recommended but do it slowly cuz your account go phone locked if you set the delays too _**low**_)

Main and alt or alt only?

**Comment by Vedza** [comment]
Alts only
