### ISSUE TITLE
NitroSniper Errorlog

### ISSUE THREAD

**Issue by FeelsBadMan1** [Vedza/NitroSniperGo#222]
Hello,
I sucessfully installed go and started the Sniper.
I used nohup ./NitroSniperGo to start it & tail -f nohup.out to see the updated output.
It alredy worked and joined some Giveaways etc. however after some time it print out following errors listed on the Screenshot i took:
![image](https://user-images.githubusercontent.com/40109798/111614785-4b426a80-87e0-11eb-9f71-3c712e9a9c1a.png)

would be nice, if someone is able to help me with that.

**Comment by Vedza** [comment]
I'd say you won a giveaway and the bot tried to send a dm to host, but he has his dm closed. Or maybe it found the wrong host idk.

**Comment by FeelsBadMan1** [comment]
Okey. Im not exactly sure what you mean / what i should send you...

**Comment by Vedza** [comment]
Try to find what giveaway you won and try to dm the host of the giveaway pls.

**Comment by FeelsBadMan1** [comment]
well that woud take long i got many alts and i would need to login 1 by 1 to see the usernames

**Comment by Vedza** [comment]
Oh yeah I forgot you have 1k alts 😆 
Then, I'll try to reproduce the bug and fix it.

**Comment by FeelsBadMan1** [comment]
oh okey. no problem have a nice day :D

**Comment by Vedza** [comment]
Probably because the account need phone verification, so it can't dm host.
I don't think I can debug and fix that

**Comment by FeelsBadMan1** [comment]
ah okey then i will generate phoneverified accounts if im at home
