### ISSUE TITLE
Sniper wont dm hoster

### ISSUE THREAD

**Issue by FeelsBadMan1** [Vedza/NitroSniperGo#223]
Hello,
I used the Sniper to snipe a few codes. However, after some time i noticed, that the Sniper not let my accounts dm the hoster.
In result they reroll the Giveaway so i aint get any nitro. Would be nice, if the Developer of the Sniper could fix that somehow.
It is sending a Message to my webhook that i won the giveaway & print it into the terminal. however its a bit useless for me if it is not dming the hoster. Proably because accounts need Phoneverification and cant dm others but im not exactly sure about it.

**Comment by Vedza** [comment]
> Proably because accounts need Phoneverification and cant dm others but im not exactly sure about it.

Or because the sniper doesn't work with the bot that did the giveaway
