### ISSUE TITLE
Feature request: add server sniper blacklist

### ISSUE THREAD

**Issue by snuckdev** [Vedza/NitroSniperGo#230]
Hey! Could you add a blacklist for sniping on servers? Like don't snipe on a specific server. Thanks!

**Comment by JohnShiozo** [comment]
this suggestion is poggers

**Comment by snuckdev** [comment]
No, only for specific servers, via ID.

**Comment by snuckdev** [comment]
And yes, I want a blacklist to disable sniping in some servers.

**Comment by Vedza** [comment]
> No, only for specific servers, via ID.

It's already the case for giveaway
```json5
 "giveaway": {
    "enable": true,
    "delay": 5,
    "dm": "Hey, I won a giveaway !", 
    "dm_delay": 10, 
    "blacklist_words": [ 
      "test",
      "ban"
    ],
    "whitelist_words": [
      "nitro"
    ],
    "blacklist_servers": [ // IDs of servers you don't want the giveaway joiner to work on
      ""  
    ]
  },
```

> And yes, I want a blacklist to disable sniping in some servers.

I'll add a global blacklist later

**Comment by Vedza** [comment]
Done
