### ISSUE TITLE
Should `main_sniper` be on to claim ONLY from alts?

### ISSUE THREAD

**Issue by Spinicle** [Vedza/NitroSniperGo#235]
Should `main_sniper` be on to claim only from alts or should it be off?

Add me on discord Senpai Spinicle#0001

**Comment by Vedza** [comment]
If you set it to true it will claim on both.
But it's quite useless because all code from alts will still be claimed on main.

**Comment by Spinicle** [comment]
Add me Senpai Spinicle# 0001

**Comment by DarkGD123** [comment]
hmm
