### ISSUE TITLE
Maybe add a Badge to Nitro Sniper GUI to stop some confusion for newbies?

### ISSUE THREAD

**Issue by PeterStrick** [Vedza/NitroSniperGo#238]
Maybe, adding a Badge like this:

[![Nitro Sniper GUI Ad](https://img.shields.io/badge/Use%20with%20Nitro%20Sniper%20GUI!-A%20friendlier%20and%20easy--to--use%20solution%20for%20Nitro%20Snipers.-9cf)](https://github.com/PeterStrick/NitroSniperGUI)
Code: `[![Nitro Sniper GUI Ad](https://img.shields.io/badge/Use%20with%20Nitro%20Sniper%20GUI!-A%20friendlier%20and%20easy--to--use%20solution%20for%20Nitro%20Snipers.-9cf)](https://github.com/PeterStrick/NitroSniperGUI)`

at the top or somewhere in the readme.md file or a link would stop some confusion for newbies and beginners about setting up the Nitro Sniper and using it, if they prefer not to use Heroku or repl.it.

It would also allow them, to automatically Update the Nitro Sniper at ease.

Any thoughts?

**Comment by Vedza** [comment]
I'm sorry but I cannot be 100% sure that you didn't change the code and put something bad in it or that you'll not do that in the future.
And I don't think there is an easier way than heroku to use the sniper, you just need to create an account and click on buttons.

**Comment by PeterStrick** [comment]
> I'm sorry but I cannot be 100% sure that you didn't change the code and put something bad in it or that you'll not do that in the future.
> And I don't think there is an easier way than heroku to use the sniper, you just need to create an account and click on buttons.

I'm just downloading the latest release from your repo and just release a new version of the Nitro Sniper GUI with it, I don´t have any intentions to cause any harm, second I don´t really understand go, as I only develop in VB .Net 😅. Well, at least I learned a few things while developing it.
