### ISSUE TITLE
Repl is allways getting rate limitted

### ISSUE THREAD

**Issue by ItzDrWaffle** [Vedza/NitroSniperGo#243]
Repl is allways getting rate limitted

**Comment by DarkGD123** [comment]
This is not a bug, repl.it is just trash

**Comment by DarkGD123** [comment]
> This is not a bug, repl.it is just trash

Not really but it gets rate limited real quick cuz i dont know, probably discord limitation

**Comment by ItzDrWaffle** [comment]
is there any way to fix it?

**Comment by DarkGD123** [comment]
No, i guess, but due to some limitations, you might need to swap to heroku (its less rate limited compare to repl.it)

**Comment by ItzDrWaffle** [comment]
MY heroku app wont show up how to fix?

**Comment by DarkGD123** [comment]
wont show?


Just follow the installation

**Comment by ItzDrWaffle** [comment]
like i cant enable sniper

**Comment by DarkGD123** [comment]
Go to resources page then enable the sniper

**Comment by ItzDrWaffle** [comment]
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by DarkGD123** [comment]
You are viewing the app not Managing It

**Comment by ItzDrWaffle** [comment]
How do  i manage

**Comment by ItzDrWaffle** [comment]
how do i know its working

**Comment by DarkGD123** [comment]
to check the resources page, there should be the 3 stacked line in the middle of your screen (not sure cuz im on mobile)

**Comment by Vedza** [comment]
https://github.com/Vedza/NitroSniperGo/discussions/236#discussioncomment-560078
