### ISSUE TITLE
Path Error

### ISSUE THREAD

**Issue by itsdux** [Vedza/NitroSniperGo#244]
When I run the sniper I get this err:

`[x] Failed read file:  open settings.json: The system cannot find the file specified.`
Even tho settings.json exists.

**Comment by Vedza** [comment]
Hi,
What OS do you use ?
Did you run it from terminal ?
DI you run it from a shortcut ?

**Comment by itsdux** [comment]
I use windows, ran it from exe.

**Comment by Vedza** [comment]
Can you send me a screenshot of the content of the folder to understand why you got this error pls ?

**Comment by itsdux** [comment]
I've restarted my pc and now works properly, thanks for helping anyways!
