### ISSUE TITLE
Does the sniper only snipe giveaways that are whitelisted?

### ISSUE THREAD

**Issue by Patrick187** [Vedza/NitroSniperGo#245]
Does the sniper only snipe giveaways that are whitelisted? or snipes everything but ignores "blacklisted" ones.
because I want to bot to snipe every giveaway and not only nitro related giveaways.
thank you.

**Comment by Vedza** [comment]
You need to let whitelist empty for that.
It will join every giveaway except ones with "test" or "ban" in this case.

```json
 "blacklist_words": [ 
      "test",
      "ban"
    ],
 "whitelist_words": [ ],
```
