### ISSUE TITLE
Not working on heroku

### ISSUE THREAD

**Issue by joao44289** [Vedza/NitroSniperGo#246]
The deployment goes smoothly on heroku. I add my token to the config (I am sure it's the correct one I double checked) and carefully changed some other settings. Just did some true-false. When I go to the check the logs after starting the worker it says "Snipping on 0 server and 0 accounts". Help?

**Comment by Vedza** [comment]
There is a bug sometime it shows "0 server" but are you sure you have "0 accounts" ?

**Comment by joao44289** [comment]
I try only adding my token and not touching any other settings and that worked. Next I tried to change settings and it no longer worked. I'll add what I changed. 

> },
  "status": {
    "main": "",
    "alts": "invisible"
  },
  "nitro": {
    "max": 2,
    "cooldown": 24,
    "main_sniper": false,
    "delay": true
  },
  "giveaway": {
    "enable": true,
    "delay": 1,
    "dm": "",
    "dm_delay": 25,
    "blacklist_words": [
      "bot",
      "test",
      "ban"
    ],
    "whitelist_words": [
      "nitro"
    ],
    "blacklist_servers": []
  },
  "invite": {
    "enable": true,
    "delay": {
      "min": 10,
      "max": 20
    },
    "max": 10,
    "cooldown": 6
  },
  "privnote": {
    "enable": false
  },
  "webhook": {
    "url": "",
    "good_only": false
  },
  "blacklist_servers": []
}

**Comment by Vedza** [comment]
You disable `main_sniper` so if you don't have any alts it won't do anything

**Comment by joao44289** [comment]
Oh, not even the giveaways? I'm not interested in Nitro, so I disabled that. I am now trying it out without changing any of the settings. I did a test giveaway in my own server using another account and the account with the sniper is not joining. I used GiveawayBot#2381. Not sure that one if that one is supported.

**Comment by Vedza** [comment]
If you disable `main_sniper`, main won't snipe anything so I must change that. If you enable it, it should work with GiveawayBot#2381.

**Comment by joao44289** [comment]
This time before deploying it to Heroku I made sure  `main_sniper:true` and it's still not entering the giveaway. It should be working because it says "Sniping on 5 servers and 1 account"

**Comment by Vedza** [comment]
Just released a new version, please open a new issue if it still doesn't work for GiveawayBot#2381.
I just tested it and it works for me.
