### ISSUE TITLE
build error on heroku

### ISSUE THREAD

**Issue by legendary0001** [Vedza/NitroSniperGo#247]
i have a selfbot for doing certain stuff and tht code is in java script and i added this sniper files and added go buildpack and go run cmd in procfile . but i get this error       

Detected the following main packages to install:
       		NitroSniperGo
       
-----> Running: go install -v -tags heroku NitroSniperGo 
build NitroSniperGo: cannot load crypto/ed25519: cannot find module providing package crypto/ed25519
 !     Push rejected, failed to compile Go app.
 !     Push failed

**Comment by Vedza** [comment]
Try to run `sudo apt-get install libasound2-dev`

**Comment by legendary0001** [comment]
;-; now i separated go code and js code . sniper is hosted on repl and js thiingy on heroku thanks for ur help

**Comment by legendary0001** [comment]
@Vedza it only works with giveaway bot and is also slow
![image](https://user-images.githubusercontent.com/76104734/114613607-34007b00-9cc1-11eb-9882-2a986dadc01d.png)

**Comment by legendary0001** [comment]
webhook doesnt work either

**Comment by Vedza** [comment]
Everything works fine for me and for everyone else so maybe it's Repl.It

**Comment by Tiebe** [comment]
For anyone still having issues with this, this is because you are using an outdated version of golang. To install the latest version uninstall the current one, `sudo apt remove golang`, then install the latest from [here](https://golang.org/dl/)
