### ISSUE TITLE
Only join giveaways on alts?

### ISSUE THREAD

**Issue by Spencer-0003** [Vedza/NitroSniperGo#251]
Hi, I was wondering if there's a way to make giveaways only work on alts? I don't want to join them on my main account.

**Comment by fazelukario** [comment]
> Hi, I was wondering if there's a way to make giveaways only work on alts? I don't want to join them on my main account.

Just change `main_sniper` option in `settings.json` from `true` to `false`.

**Comment by Spencer-0003** [comment]
Thanks! Will try that later.
