### ISSUE TITLE
Rate limited

### ISSUE THREAD

**Issue by Kenzhinn** [Vedza/NitroSniperGo#252]
It says that I am being rate limited. Is that why I can't redeem a code? also how can I fix it. Noob here
![Screenshot 2021-04-17 023402](https://user-images.githubusercontent.com/44579139/115069027-9c4f9680-9f25-11eb-8e52-fa828f1c1bd9.png)

**Comment by uniedit0001** [comment]
same

**Comment by onmikron1** [comment]
same

**Comment by ibndiaye** [comment]
hello, i'm not experiencing it on my side. but i had it once when a friend of mine started mass sending nitro codes. could be that causing it. also i'm running it on heroku, maybe try hosting it there

**Comment by DarkGD123** [comment]
This is normal, just restart the app then yeah, thats all ***i reset mine everytime if this happens to me btw***

This isnt a bug too lol

**Comment by DarkGD123** [comment]
small tip: Try not to put 4 or more alts in a same server, you can get rate limited pretty quick (as of my experiences and some test of course)
