### ISSUE TITLE
Error opening connection for Nz(my token) websocket: close 4004: Authentication failed.

### ISSUE THREAD

**Issue by p007master** [Vedza/NitroSniperGo#259]
**Please check previous issues before opening a new one as well as [Know Issues](https://github.com/Vedza/NitroSniperGo#known-issues)**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by p007master** [comment]
what can i do

**Comment by Ender786** [comment]
This is not a bug, you have entered an incorrect token.

**Comment by Ender786** [comment]
Watch a tutorial to see how to get your token.
