### ISSUE TITLE
discord removed my actual nitro and my nitro from inventory won't start

### ISSUE THREAD

**Issue by iulian12h** [Vedza/NitroSniperGo#260]
**Please check previous issues before opening a new one as well as [Know Issues](https://github.com/Vedza/NitroSniperGo#known-issues)**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Vedza** [comment]
It's not a bug.
This is the first time I hear something like that. Can you create a Discussion so everyone can see it and maybe we can see if someone else had this issue.
