### ISSUE TITLE
It doesn't send message to webhook when claiming a nitro successfully

### ISSUE THREAD

**Issue by Weknox** [Vedza/NitroSniperGo#264]
It runs on a VPS and when it claims a nitro it gives an error like this on console.

> ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
> ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
> ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
> ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
> ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
> ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default

It is probably because VPS doesn't have a speaker to play the sound. Is there any way to fix this or disable the play sound on the successful claim?

**Comment by Vedza** [comment]
` sudo apt-get install libasound2-dev`
