### ISSUE TITLE
''You need to verify your account in order to perform this action.''

### ISSUE THREAD

**Issue by JarnoXYZ** [Vedza/NitroSniperGo#265]
In the webhook, it will say sniped but the response is:
''Response
You need to verify your account in order to perform this action.''

Why is this? It's not Xbox Game Pass because I checked the link and there was a nitro classic in there too.

**Comment by Vedza** [comment]
Please don't put bug tag when it's absolutely not a bug.

Maybe you can't claim Nitro until you verify your account with a phone number.

**Comment by JarnoXYZ** [comment]
Hello, sorry for putting the bug tag.

I have put a phone number on every alt that I used. (Because I joined so many servers I was forced to verify)

**Comment by Ender786** [comment]
If you have actually verified all your alts with a phone number then you shouldn't get that error, my friend had the same issue and all he had to do was verify his phone number, it could also be the emails for the accounts have not been verified.
