### ISSUE TITLE
Alt doesnt join any server

### ISSUE THREAD

**Issue by inverspe** [Vedza/NitroSniperGo#269]
I set the auto joiner on but my alt doesnt join any server I sent my alt a dm with discord link with 50000 members didnt work

**Comment by inverspe** [comment]
also is there a feature where you can set the sniper to join only servers that has 1000 members above only?

**Comment by Andrzejone** [comment]
yep. confirm. Not working at all

**Comment by DarkGD123** [comment]
*the invite sniper has min and maximum delays (mins)*

**Comment by Andrzejone** [comment]
btw. Shou;d I care by this error
![image](https://user-images.githubusercontent.com/39127677/116944932-bb189180-ac76-11eb-86a7-244bc39ad55d.png)

**Comment by Viktigboy** [comment]
i have the same issue.
I have 3 alts, and none of them are joining servers

**Comment by Vedza** [comment]
Feature disabled for now
