### ISSUE TITLE
high latency on heroku

### ISSUE THREAD

**Issue by lasagnab320** [Vedza/NitroSniperGo#273]
I have been experiencing some high latency snipes (usually 65+ ms and occasionally 100+ ms) on heroku, Any fixes?

**Comment by Vedza** [comment]
Hey,
It depends on Heroku servers do we can't do much about it. Maybe change the region of the server ? 🤔 
But it's still decent

**Comment by lasagnab320** [comment]
ill try that, thanks!

**Comment by Asvarius** [comment]
> ill try that, thanks!

It's actually not that big of a delay tho, 100 ms is 0,1 seconds, thats way faster than a human reaction

**Comment by Asvarius** [comment]
you should be getting the message that it was redeemed already. Almost everytime it means that the guy faked a drop
