### ISSUE TITLE
The sniper doesn't detects codes/gifts

### ISSUE THREAD

**Issue by Vulkanik** [Vedza/NitroSniperGo#274]
Hey, I am not really sure if it's a problem only with me, however the snipers doesn't detects codes/gifts for some reason. I am sure that the account received the gift however it haven't detected it. Sorry if I created an issue in wrong category.

**Comment by Vedza** [comment]
Hi,
I'm using it right now and it's working. Maybe you don't receive  message on webhook because you tried with old or fake codes, but it should still appear on the console running the sniper.

**Comment by Vulkanik** [comment]
The problem is that it doesn't appear in the console, it was working fine, however I have restarted it (closed & opened it again) and it stopped receiving the codes (at least they aren't appearing in the console).

**Comment by Vedza** [comment]
Did it print `[+] Sniper is ready`?

**Comment by Vulkanik** [comment]
Yes, it printed that. Maybe you could also try restarting the sniper for yourself and see if it's working, only if you want.

**Comment by Vedza** [comment]
I just did it and it works for me 🤔

**Comment by Vulkanik** [comment]
Interesting, then I have no idea why it doesn't work, my friend just messaged me and told me the same, that it doesn't work for him. I have tried sending DM gifts to the accounts, I even posted the gifts in the server where the accounts are and it haven't detected anything. I'll try to figure it out somehow.

**Comment by Ender786** [comment]
@Vedza There is something wrong with the sniper as I am having the same issue, if you send a code from the account you are sniping on it will show up in the console but if you get someone else to send a code it doesn't detect it.

**Comment by Ender786** [comment]
I have also just tested it with a simple python sniper and its the same issue, it just detects codes if they are sent by the account you are sniping on but if you use another account it doesn't detect it.

**Comment by Vedza** [comment]
Ok I tested and it doesn't work for me neither but it still work for some people I don't understand why.
I'm working on it rn.

**Comment by snuckdev** [comment]
Same here, I tested with my old codes and it doesn't detects.

**Comment by Ender786** [comment]
Some screenshots verifying the api change for discord:
![image](https://user-images.githubusercontent.com/54211493/116793165-f2dbd980-aabc-11eb-9311-aacc74045eab.png)
![image](https://user-images.githubusercontent.com/54211493/116793169-f707f700-aabc-11eb-8fc0-b8d992338b39.png)
![image](https://user-images.githubusercontent.com/54211493/116793171-f96a5100-aabc-11eb-8a05-38c74a8f51e7.png)
![image](https://user-images.githubusercontent.com/54211493/116793175-fbccab00-aabc-11eb-9881-404b3a16144f.png)

These are from other sniper developers

**Comment by Ender786** [comment]
@Vedza any updates? If not good luck trying to find a bypass, hope you succeed.

**Comment by snuckdev** [comment]
@Reware53
@JohnShiozo
Más notícias

**Comment by Ender786** [comment]
@Vedza not sure if this will help but this person is claiming to have found a bypass:
![Screenshot_20210501-220359_Discord](https://user-images.githubusercontent.com/54211493/116794958-291f5600-aac9-11eb-93a7-4c25f6827338.png)

**Comment by Vedza** [comment]
Ok so good new I found a solution.
But it require me to recode almost all the sniper 😢 
![image](https://user-images.githubusercontent.com/28839427/116808529-95d23900-ab39-11eb-86ec-0b10ef3ecc9b.png)

**Comment by Ender786** [comment]
> Ok so good new I found a solution.
> But it require me to recode almost all the sniper 😢

oh damn, well good luck with that.

**Comment by snuckdev** [comment]
> Ok so good new I found a solution.
> But it require me to recode almost all > the sniper 😢 
Oh😔
Buy will It affect it's speed?

**Comment by snuckdev** [comment]
https://github.com/slow/nitro-sniper
this sniper is working, I tested it

**Comment by Ender786** [comment]
> https://github.com/slow/nitro-sniper
> this sniper is working, I tested it

yeah your right, but how is that one working and this one isn't...

**Comment by snuckdev** [comment]
> yeah your right, but how is that one working and this one isn't...
I don't know, maybe a specific error with discordgo or something else

**Comment by Ender786** [comment]
Yep I think you are right, I just tried my python sniper again and for some reason its working now but yesterday it wasn't, its very strange but its still doesn't work with snipers coded in go

**Comment by Vulkanik** [comment]
Hey @Vedza, I was wondering if we could get in touch on Discord or somewhere else. If you could, please add me on Discord (KingKong#7596) or send me your username so I can add you.

**Comment by snuckdev** [comment]
Any news? Most snipers are working rn

**Comment by Vedza** [comment]
I already made a basic sniper so It's possible to fix it but it require a bit of work.
And some guy is paying me to fix his go sniper and I'm working on other projects so I don't think i'll fix mine soon because of a lack of time

**Comment by snuckdev** [comment]
And also, is it a problem with discordgo? Because d.py and d.js made snipers are working fine today

**Comment by Vedza** [comment]
Yes

**Comment by Vedza** [comment]
Actually there is a way easier solution (thanks [Vulkanik](https://github.com/Vulkanik]) 🙏 )
And it's available for Windows and on heroku right now !

**Comment by snuckdev** [comment]
For me it isn't working right now.

**Comment by snuckdev** [comment]
Redeployed it to heroku but no success.

**Comment by Vedza** [comment]
I don't understand it works for me this time 🤔 
Maybe try with an other region on heroku.
Is any one else having this issue ?

**Comment by idkwhatnamele** [comment]
I tried the new one but it doesn't detect any codes I also tried switching regions but still the same issue.

**Comment by Vedza** [comment]
> I tried the new one but it doesn't detect any codes I also tried switching regions but still the same issue.

https://github.com/Vedza/NitroSniperGo/issues/276

**Comment by MinedAnemone34** [comment]
I am using a customized version of vedza's sniper and am experiencing the same problem.
here is what I know now.
1. if I create a discord bot and use its token, it works fine.
2. if I use a user's token, it only detects its own messages and messages it's been mentioned by.
I hope these will help you in some way.
