### ISSUE TITLE
Newest fix not working well

### ISSUE THREAD

**Issue by snuckdev** [Vedza/NitroSniperGo#276]
The Discord API has changed, but this sniper was supposed to work. Whenever I try to run it, it appears to work, but it remains not detecting any code and errors dropping in the console.
Console print: http://pays.host/uploads/1b50eb65-7985-4a6d-99ca-b096c98c31f7/pa8Ua2Tj.png

**Comment by Ender786** [comment]
Same here

**Comment by Vedza** [comment]
OK I think you're in a lots of servers and because the new method require one more request every single message, you are being rate limited because the sniper is doing too many requests 😭

**Comment by Asvarius** [comment]
I'm using the release before that and its working great :)

**Comment by Vedza** [comment]
the solution available now is quite bad and I do not recommend it because it takes a lot of ram and get your rate limited really fast.
So maybe that's why you don't see anything.
I'll try to release the other one in the next weeks, or maybe discordgo will be updated idk

**Comment by Ender786** [comment]
> OK I think you're in a lots of servers and because the new method require one more request every single message, you are being rate limited because the sniper is doing too many requests 😭

ahh, no wonder my rdp got rate limited

**Comment by Ender786** [comment]
> I'm using the release before that and its working great :)

How though, the old version stopped working...

**Comment by snuckdev** [comment]
>OK I think you're in a lots of servers and because the new method require one more request every single message, you are being rate limited because the sniper is doing too many requests 😭

Yeah i'm in like 545 servers

**Comment by idkwhatnamele** [comment]
same issue here, sniper doesn't detect any codes

**Comment by Vedza** [comment]
> same issue here, sniper doesn't detect any codes



> OK I think you're in a lots of servers and because the new method require one more request every single message, you are being rate limited because the sniper is doing too many requests 😭



> the solution available now is quite bad and I do not recommend it because it takes a lot of ram and get your ip rate limited really fast.
> So maybe that's why you don't see anything.
> I'll try to release the other one in the next weeks, or maybe discordgo will be updated idk

**Comment by ogli-tree** [comment]
If you have the time I'd love to hear your solution because my personal sniper stopped working as well and I can't for the life of me come up with a solution.

**Comment by snuckdev** [comment]
There isnt a solution, It isnt working

**Comment by ogli-tree** [comment]
> There isnt a solution, It isnt working

Sorry for the confusion, I was asking the developer about his new solution he will be implementing.

**Comment by Vedza** [comment]
> Sorry for the confusion, I was asking the developer about his new solution he will be implementing.

The new solution id the library `disgord` but it needs to be edited a little bit to work for self bot

**Comment by snuckdev** [comment]
> The new solution id the library disgord but it needs to be edited a little bit to work for self bot

But it has bugs if your alts are on many servers, right?

**Comment by Vedza** [comment]
> > The new solution id the library disgord but it needs to be edited a little bit to work for self bot
> 
> But it has bugs if your alts are on many servers, right?

It looks like not with `disgord`

**Comment by Vedza** [comment]
Hey, I just released a new version. Invite sniper and privnote sniper is disabled but I hope everything else works fine !
