### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by 3y3lone** [Vedza/NitroSniperGo#279]
Does this work on mac? if it does how do i set it up i tried doing go build (the file name) but it keeps on saying (filename) is not in GOROOT

**Comment by Vedza** [comment]
You just need to run `go build` while being in the sniper directory and that's all.
But as you can see in the ReadMe I wouldn't recommend using the sniper right now

**Comment by 3y3lone** [comment]
It says permission denied

**Comment by Vedza** [comment]
If you download the release you need to run `chmod +x NitroSniperGo`
