### ISSUE TITLE
Error With Raspberry Pi!

### ISSUE THREAD

**Issue by qmitrox** [Vedza/NitroSniperGo#280]
pi@pi:~/Sniper-GO $ go run sniper.go
build NitroSniperGo: cannot find module for path crypto/ed25519
pi@pi:~/Sniper-GO $

![image](https://user-images.githubusercontent.com/61907335/117306717-38fbb900-ae80-11eb-9d5d-ff2b556c19b3.png)

Please help me!

**Comment by Vedza** [comment]
Hey, Please read the README.
Everything is on it 👍

**Comment by qmitrox** [comment]
https://github.com/Vedza/NitroSniperGo/blob/master/README.md You mean this? what is wrong i have read this README File

This: 
root@pi:/home/pi/Sniper-GO# go run sniper.go
# runtime
/usr/local/go/src/runtime/hashmap.go:89:2: empty redeclared in this block
        previous declaration at /usr/local/go/src/runtime/chan.go:428:22
/usr/local/go/src/runtime/map.go:65:2: bucketCntBits redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:64:18
/usr/local/go/src/runtime/map.go:66:2: bucketCnt redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:65:23
/usr/local/go/src/runtime/map.go:77:2: maxKeySize redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:74:17
/usr/local/go/src/runtime/map.go:83:2: dataOffset redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:83:4
/usr/local/go/src/runtime/map.go:94:2: evacuatedX redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:91:19
/usr/local/go/src/runtime/map.go:95:2: evacuatedY redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:92:19
/usr/local/go/src/runtime/map.go:96:2: evacuatedEmpty redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:90:19
/usr/local/go/src/runtime/map.go:97:2: minTopHash redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:93:19
/usr/local/go/src/runtime/map.go:100:2: iterator redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:96:16
/usr/local/go/src/runtime/map.go:100:2: too many errors

Go Version:
go version go1.16.3 linux/arm

**Comment by qmitrox** [comment]
![image](https://user-images.githubusercontent.com/61907335/117319156-55e9b980-ae8b-11eb-9a0b-8333934dd310.png)

**Comment by Vedza** [comment]
There isn't any `go run sniper.go` in the README
Try to disable privnote sniper if it crash again
