### ISSUE TITLE
Rate Limited for 30 mins when excecuting

### ISSUE THREAD

**Issue by aleckslol** [Vedza/NitroSniperGo#283]
Every time I use the sniper, it rate limits discord on my entire IP for 30 mins.. this makes me only be able to use it with a vpn. It is a bit annoying, and sometimes doesn't even scan any codes at all. If there could be some fix for this it would be absolutely great. I love using the sniper, and had no issues but success so far. 

I think it is due to the heavy amount of servers I am in, or even the discord API changing. I am not too sure, and this started happening after my old NitroSniperGo version died, and I had to update into the new one. If any fix is known for this, or a heads up about this issue being known and worked on, it would be great!

**im an absolute idiot so if i am doing something wrong i really do apologize.**

**Comment by Vedza** [comment]
https://github.com/Vedza/NitroSniperGo#update-0504-

Yeah it's because of the api change, I found a quick fix to bypass it but it's pretty bad :/
