### ISSUE TITLE
Sniper heroku error

### ISSUE THREAD

**Issue by Endermagegg** [Vedza/NitroSniperGo#284]
![image](https://user-images.githubusercontent.com/79878252/118365297-70e6b880-b572-11eb-9c2e-c4ad30d875bd.png)
When i click deploy to heroku show that

**Comment by Vedza** [comment]
It works for me 👍 
https://heroku.com/deploy?template=https://github.com/Vedza/NitroSniperGo/tree/heroku

**Comment by Endermagegg** [comment]
> It works for me 👍
> https://heroku.com/deploy?template=https://github.com/Vedza/NitroSniperGo/tree/heroku

But dont for me...

**Comment by Vedza** [comment]
Maybe there is a problem with Heroku as config file is working for me.
