### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by screamz2k** [Vedza/NitroSniperGo#285]
![image](https://user-images.githubusercontent.com/78593516/118375752-01011e00-b5c4-11eb-8111-6e8dcd85875b.png)

**Comment by Vedza** [comment]
Have you tried that ?
```
go mod download
go build
./NitroSniperGo
```

**Comment by screamz2k** [comment]
yes

**Comment by screamz2k** [comment]
it shows the same error

**Comment by Vedza** [comment]
can you try `go mod vendor` pls

**Comment by screamz2k** [comment]
ok

**Comment by screamz2k** [comment]
it showed the imports the i tried to run it again and the same errors showed up

**Comment by Vedza** [comment]
Ok so I just made an update, can you pull it and try again `go mod download`

**Comment by screamz2k** [comment]
ok

**Comment by screamz2k** [comment]
![Uploading image.png…]()

**Comment by Vedza** [comment]
I can't see your image

**Comment by screamz2k** [comment]
![image](https://user-images.githubusercontent.com/78593516/118376305-8508d500-b5c7-11eb-8eb0-118050f34245.png)

**Comment by screamz2k** [comment]
now?

**Comment by Vedza** [comment]
I can see it now. Can you run `go version` to give me your go version pls

**Comment by screamz2k** [comment]
![image](https://user-images.githubusercontent.com/78593516/118376435-3445ac00-b5c8-11eb-8a62-73ee14d76669.png)

**Comment by screamz2k** [comment]
wont answer now going off but will look at you answer tmw :)

**Comment by Vedza** [comment]
You are using gccgo compiler instead of the standard go compiler gc.

**Comment by screamz2k** [comment]
Now its working with compiling thanks :)
