### ISSUE TITLE
Does the sniper automatically joins new servers and how does it do so? I'm sorry for this basic question. I'm new to all this. Also, What is privnote? I have it enabled.

### ISSUE THREAD

**Issue by made101** [Vedza/NitroSniperGo#288]
Read Title please.

**Comment by GAMINGMarcellYT** [comment]
Privinote is a website where you can type something is get a link and if someone used the link its not useble again

**Comment by made101** [comment]
> Privinote is a website where you can type something is get a link and if someone used the link its not useble again

and how does the sniper join new servers?

**Comment by Vedza** [comment]
I disabled both features in the code after the last update because of API update.
