### ISSUE TITLE
Crashes bcs of wrong json :(

### ISSUE THREAD

**Issue by Superbulzo** [Vedza/NitroSniperGo#291]
![image](https://user-images.githubusercontent.com/69388805/118454061-39097d80-b6f8-11eb-8724-d7b31d009806.png)

My config:

{
  "tokens": {
    "main": "<my_token>",
    "alts": [
      "<other_token>",
      "<other_token>",
      "<other_token>"
    ]
  },
  "status": {
    "main": "online",
    "alts": "invisible"
  },
  "nitro": {
    "max": 10,
    "cooldown": 24,
    "main_sniper": true,
    "delay": true
  },
  "giveaway": {
    "enable": true,
    "delay": 15,
    "dm": "<random_message>",
    "dm_delay": 25,
    "blacklist_words": [
      "bot",
      "test",
      "ban"
    ],
    "whitelist_words": [
      "nitro",
      "boost",
      "account"
    ],
    "blacklist_servers": [
      "<server_id>"
],
  },
  "invite": {
    "enable": true,
    "delay": {
      "min": 10,
      "max": 20
    },
    "max": 10,
    "cooldown": 6
  },
  "privnote": {
    "enable": false
  },
  "webhook": {
    "url": "<weebhook_link>",
    "good_only": false
  },
  "blacklist_servers": [
      "<server_id>"
],
}

**Comment by Superbulzo** [comment]
what happened? did you replied? i can't see it

**Comment by Vedza** [comment]
remove `,`
```
"blacklist_servers": [
"<server_id>"
], <- here
```

**Comment by Superbulzo** [comment]
thanks duuude

**Comment by Superbulzo** [comment]
![image](https://user-images.githubusercontent.com/69388805/118458010-97376000-b6fa-11eb-93c8-b1551e6d4cfe.png)

**Comment by Superbulzo** [comment]
there is already

**Comment by Vedza** [comment]
There is 2
```
"blacklist_servers": [
"<server_id>"
],
```

on your issue, And both have a comma at the end and shouldn't

**Comment by Superbulzo** [comment]
oh removing

**Comment by Superbulzo** [comment]
removed but still the same issue

**Comment by Vedza** [comment]
maybe put your config here https://jsonformatter.curiousconcept.com/# and it will fix it

**Comment by Superbulzo** [comment]
thx dude

**Comment by Superbulzo** [comment]
fixeeeed thxxx

**Comment by Superbulzo** [comment]
dude the only problem is that now i don't get messages in the webhook

**Comment by Vedza** [comment]
yeah I know I'll check later 👍

**Comment by Superbulzo** [comment]
k
