### ISSUE TITLE
Sniper suggestion

### ISSUE THREAD

**Issue by made101** [Vedza/NitroSniperGo#294]
Is there a way to make the sniper snipe the codes faster like in 300ms instead of 500-600ms? Since 2 days I'm always getting the code has been redeemed already.

![Screenshot (79)_LI](https://user-images.githubusercontent.com/77076813/118604541-ea7ce180-b7d2-11eb-9a67-114bb890b9e6.jpg)

**Comment by Vedza** [comment]
People send already redeemed code all the time. And it depends on your internet speed. 
You can use heroku and you'll get better delay

**Comment by made101** [comment]
The thing is I don't know how heroku functions or works and the commands I need to use to launch the application. I deployed the app but I don't understand how to run it.

**Comment by Vedza** [comment]
![image](https://user-images.githubusercontent.com/28839427/118608540-16d83400-b7ba-11eb-9bf9-a597b42a522e.png)

**Comment by made101** [comment]
Thank you very much. I wasn't able to fully understand it. Now I do.
