### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by bara-lol** [Vedza/NitroSniperGo#295]
**Please check previous issues before opening a new one as well as [Know Issues](https://github.com/Vedza/NitroSniperGo#known-issues)**

**Describe the bug**
When I open the sniper the command prompt just sits idle with the line blinking, doesnt start and doesnt show the usual discord sniper text. I've checked my token but it has not changed and I keep updating the settings file with it.

**To Reproduce**
1. Open sniper

**Expected behavior**
I expected the sniper to open and start looking for nitro drops but that doesnt happen.

**Screenshots**

![Screenshot_85](https://user-images.githubusercontent.com/84264737/118646791-51a59080-b7e9-11eb-9d25-066e3d420d70.png)

**Comment by Koolwiza** [comment]
You just have to wait for there to be valid entries

**Comment by C0DE4ME** [comment]
> You just have to wait for there to be valid entries

mine dose the same thing, even after waiting 
think bara are expecting to see a "[+] Sniper is ready" and are unsure if its running
![Capture](https://user-images.githubusercontent.com/78388363/119054518-c289ab80-b995-11eb-8969-9f2be6f9a145.JPG)

**Comment by C0DE4ME** [comment]
hello bara
after having the same issue you have i believe i have found a fix
it has something to do with 2step authentication on your discord acc and your discord token
2step discord accs seem to have rotating tokens and makes it hard to validate this session within the software
the fix:
what i did is disabled my authentication ( !SECURITY RISK! )
after that discord changed my accounts token twice within an hour and after waiting 3 hours it seems to have a static (nonchanging) token
i also put the token in the alt .txt file
hope this helps u and others : ) 
![image](https://user-images.githubusercontent.com/78388363/119062387-accfb280-b9a4-11eb-9413-ea8dc37f614e.png)

**Comment by bara-lol** [comment]
> hello bara
> after having the same issue you have i believe i have found a fix
> it has something to do with 2step authentication on your discord acc and your discord token
> 2step discord accs seem to have rotating tokens and makes it hard to validate this session within the software
> the fix:
> what i did is disabled my authentication ( !SECURITY RISK! )
> after that discord changed my accounts token twice within an hour and after waiting 3 hours it seems to have a static (nonchanging) token
> i also put the token in the alt .txt file
> hope this helps u and others : )
> ![image](https://user-images.githubusercontent.com/78388363/119062387-accfb280-b9a4-11eb-9413-ea8dc37f614e.png)

thank you
