### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by inverspe** [Vedza/NitroSniperGo#297]
When my account snipes a nitro code it says "400: Bad Request" after the sniped code message

**Comment by andersfylling** [comment]
Could you provide some more insight here? Especially code. @Vedza could you point me to what disgord methods are used in this case?

**Comment by Vedza** [comment]
Don't worry it's not a request made from you library 👍

**Comment by Vedza** [comment]
Went back to the old version where everything was working fine. Please open a new issue if this issue still exists
