### ISSUE TITLE
[Bug] Giveway autoreactor reacts at random seconds

### ISSUE THREAD

**Issue by Sovex666** [Vedza/NitroSniperGo#306]
I have giveway dealy reactor set at 600 but it reacts between 3 seconds to 60 seconds.

**Comment by Vedza** [comment]
It's not random, it's what you put in the settings.
Unless there is a bug.

**Comment by Sovex666** [comment]
I've put this 
"giveaway": {
    "enabled": true,
    "delay": 600,
    "dm": true,
    "dmMessage": "Hello I won give me prize.",
    "dmDelay": 300,
    "blacklistedWords": [
and I get maximum 60 seconds of reaction dealy

**Comment by Sovex666** [comment]
@Vedza 
![Screenshot_1](https://user-images.githubusercontent.com/84601115/119730407-5966d400-be7e-11eb-9b67-870989f422c7.png)

**Comment by Vedza** [comment]
Went back to the old version where everything was working fine. Please open a new issue if this issue still exists
