### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by clarielle** [Vedza/NitroSniperGo#31]
I'm on mac and set up everything in settings.json, but when I open NitroSniperGo it just tells me that file doesn't exist. 
![Screen Shot 2020-10-20 at 2 25 33 PM](https://user-images.githubusercontent.com/68574128/96646042-5ef4ae00-12e0-11eb-94cf-cb0d0fffb116.png)

**Comment by Vedza** [comment]
The program open the json file in the directory where it's executed. So you must `cd ~/Downloads/NitroSniperGo` before `./NitroSniperGo`. If it doesn't work send me your discord here

**Comment by vinicio1** [comment]
> The program open the json file in the directory where it's executed. So you must `cd ~/Downloads/NitroSniperGo` before `./NitroSniperGo`. If it doesn't work send me your discord here

same for me, doesn't work. can you help me?. my discord is Caligula#9429
