### ISSUE TITLE
i sniped a code and this is what it said

### ISSUE THREAD

**Issue by bokoli167** [Vedza/NitroSniperGo#311]
i sniped a code but i didnt get it and he said bad request, what does that mean? here is a screensot
![Screenshot_2_LI](https://user-images.githubusercontent.com/84736995/119879445-ed46a780-bf33-11eb-977b-54ad1a4fb4c3.jpg)

**Comment by Vedza** [comment]
Went back to the old version where everything was working fine. Please open a new issue if this issue still exists
