### ISSUE TITLE
Status not working

### ISSUE THREAD

**Issue by xsplas** [Vedza/NitroSniperGo#313]
I want my alts to snipe and it look like there are offline. So the code is:
  "status": {
    "main": "offline",
    "alts": "offline"
  },

I also tried it with invisible but the accounts show online.

**Comment by Vedza** [comment]
This feature is disabled for now because of the last discord update.

**Comment by xsplas** [comment]
You know if its possible to add it again after the update?

**Comment by Vedza** [comment]
idk
