### ISSUE TITLE
Nitrosniper under Windows RDP

### ISSUE THREAD

**Issue by FeelsBadMan1** [Vedza/NitroSniperGo#319]
Hello, i tried to run the sniper on a windowsserver and installed go succesfully. however if i run go run sniper.go then i get lots of issures:
![image](https://user-images.githubusercontent.com/40109798/120761021-0c859c00-c515-11eb-94f6-8a267f3c6304.png)
and if i run the listed commands one by one it print new links and thats unlimited....

**Comment by FeelsBadMan1** [comment]
I now copy pasted all commands listed. now i see a error that tells me that the settings.json not exist. but it clearly exist in the folder:
![image](https://user-images.githubusercontent.com/40109798/120761927-fc21f100-c515-11eb-87ac-27960fa19083.png)

**Comment by PeterStrick** [comment]
> I now copy pasted all commands listed. now i see a error that tells me that the settings.json not exist. but it clearly exist in the folder:
> ![image](https://user-images.githubusercontent.com/40109798/120761927-fc21f100-c515-11eb-87ac-27960fa19083.png)

You could try to compile the sniper into an executable using:
```
go mod download
go build
```

and see if it works then.

Most issues seem to come from people who try to run the sniper directly from the .go file

**Comment by FeelsBadMan1** [comment]
yea i solved it. however i have mainsniper set to true and im not sure if that means it only snipes on main or it snipes on main & on alts....

**Comment by PeterStrick** [comment]
> yea i solved it. however i have mainsniper set to true and im not sure if that means it only snipes on main or it snipes on main & on alts....

pretty sure mainsniper being set to true means that the sniper, snipes on the main token, as well as the alt tokens.
setting it to false should force the sniper to only snipe from the alt tokens i think

**Comment by FeelsBadMan1** [comment]
oh okey. is it usual that it takes long to snipe? for me its about 100 ms - 200 ms

**Comment by FeelsBadMan1** [comment]
hmm that is my last question for now i think that i wrote above. why it will take  so long? i hosting the sniper on a windowsrdp that has upto 5GB/s up & download so the internetspped not sould be the issure. this issure just got randomly closed.... basically all Nitro it snipe is alredy redeemd because of the slow speed. maybe i need to use it on linuxserver? Im not sure about that.

**Comment by PeterStrick** [comment]
> hmm that is my last question for now i think that i wrote above. why it will take so long? i hosting the sniper on a windowsrdp that has upto 5GB/s up & download so the internetspped not sould be the issure. this issure just got randomly closed.... basically all Nitro it snipe is alredy redeemd because of the slow speed. maybe i need to use it on linuxserver? Im not sure about that.

Don´t know about the first part, but you should keep in mind, that you aren´t the only person on earth trying to snipe Nitro. There are many different Nitro Snipers out there that vary in Speed, usability, and features. Sniping Nitro successfully is determined by:

- The Speed of the Sniper
- The Network Speed of your *own* Internet, as well as Discord´s Servers
- The amount of people that are also sniping in the same server
- Luck
