### ISSUE TITLE
Json problem?

### ISSUE THREAD

**Issue by masikszabi** [Vedza/NitroSniperGo#32]
Hi, I'm keep getting the unmarshalling error right after launch. Can't figure out how to fix that

 [DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string

**Comment by Vedza** [comment]
Hi, it comes from a library I use because we're using a token that doesn't come from a bot. Some people have it and some not, but the program works fine even with this error.
