### ISSUE TITLE
PROGRAM STARTING AND CLOSING

### ISSUE THREAD

**Issue by csirkepipi** [Vedza/NitroSniperGo#320]
▓█████▄  ██▓  ██████  ▄████▄   ▒█████   ██▀███  ▓█████▄      ██████  ███▄    █  ██▓ ██▓███  ▓█████  ██▀███
▒██▀ ██▌▓██▒▒██    ▒ ▒██▀ ▀█  ▒██▒  ██▒▓██ ▒ ██▒▒██▀ ██▌   ▒██    ▒  ██ ▀█   █ ▓██▒▓██░  ██▒▓█   ▀ ▓██ ▒ ██▒
░██   █▌▒██▒░ ▓██▄   ▒▓█    ▄ ▒██░  ██▒▓██ ░▄█ ▒░██   █▌   ░ ▓██▄   ▓██  ▀█ ██▒▒██▒▓██░ ██▓▒▒███   ▓██ ░▄█ ▒
░▓█▄   ▌░██░  ▒   ██▒▒▓▓▄ ▄██▒▒██   ██░▒██▀▀█▄  ░▓█▄   ▌     ▒   ██▒▓██▒  ▐▌██▒░██░▒██▄█▓▒ ▒▒▓█  ▄ ▒██▀▀█▄
░▒████▓ ░██░▒██████▒▒▒ ▓███▀ ░░ ████▓▒░░██▓ ▒██▒░▒████▓    ▒██████▒▒▒██░   ▓██░░██░▒██▒ ░  ░░▒████▒░██▓ ▒██▒
▒▒▓  ▒ ░▓  ▒ ▒▓▒ ▒ ░░ ░▒ ▒  ░░ ▒░▒░▒░ ░ ▒▓ ░▒▓░ ▒▒▓  ▒    ▒ ▒▓▒ ▒ ░░ ▒░   ▒ ▒ ░▓  ▒▓▒░ ░  ░░░ ▒░ ░░ ▒▓ ░▒▓░
░ ▒  ▒  ▒ ░░ ░▒  ░ ░  ░  ▒     ░ ▒ ▒░   ░▒ ░ ▒░ ░ ▒  ▒    ░ ░▒  ░ ░░ ░░   ░ ▒░ ▒ ░░▒ ░      ░ ░  ░  ░▒ ░ ▒░
░ ░  ░  ▒ ░░  ░  ░  ░        ░ ░ ░ ▒    ░░   ░  ░ ░  ░    ░  ░  ░     ░   ░ ░  ▒ ░░░          ░     ░░   ░
░     ░        ░  ░ ░          ░ ░     ░        ░             ░           ░  ░              ░  ░   ░
░                   ░                           ░

panic: unaligned 64-bit atomic operation

goroutine 37 [running]:
runtime/internal/atomic.panicUnaligned()
        C:/Program Files (x86)/Go/src/runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Xadd64(0x12678614, 0x1, 0x0, 0x8c11f8, 0x1)
        C:/Program Files (x86)/Go/src/runtime/internal/atomic/asm_386.s:107 +0x11
go.uber.org/atomic.(*Uint64).Add(...)
        C:/Users/gcsti/go/pkg/mod/go.uber.org/atomic@v1.5.1/atomic.go:190
github.com/andersfylling/disgord/internal/gateway.(*client).getLogPrefix(0x12678500, 0x0, 0x11c07010)
        C:/Users/gcsti/Downloads/NitroSniperGo-master/NitroSniperGo-master/disgord@custom/internal/gateway/client.go:256 +0xa1
github.com/andersfylling/disgord/internal/gateway.(*client).reconnectLoop(0x12678500, 0x12648860, 0x11c3fcec)
        C:/Users/gcsti/Downloads/NitroSniperGo-master/NitroSniperGo-master/disgord@custom/internal/gateway/client.go:331 +0x34
github.com/andersfylling/disgord/internal/gateway.(*shardMngr).Connect(0x12652580, 0x0, 0x0)
        C:/Users/gcsti/Downloads/NitroSniperGo-master/NitroSniperGo-master/disgord@custom/internal/gateway/sharding.go:323 +0xe1
github.com/andersfylling/disgord.(*Client).Connect(0x11c78000, 0x8ca5ac, 0x11c10060, 0x1263a640, 0x0)
        C:/Users/gcsti/Downloads/NitroSniperGo-master/NitroSniperGo-master/disgord@custom/client.go:436 +0x384
github.com/andersfylling/disgord.(*Client).StayConnectedUntilInterrupted(0x11c78000, 0x8ca5ac, 0x11c10060, 0x1263a640, 0x0)
        C:/Users/gcsti/Downloads/NitroSniperGo-master/NitroSniperGo-master/disgord@custom/client.go:492 +0x4d
main.main.func1.1(0x11c78000, 0x8ca5ac, 0x11c10060)
        C:/Users/gcsti/Downloads/NitroSniperGo-master/NitroSniperGo-master/sniper.go:514 +0x35
main.main.func1(0x0, 0x0, 0x11c06fc8)
        C:/Users/gcsti/Downloads/NitroSniperGo-master/NitroSniperGo-master/sniper.go:579 +0x3ee
created by main.main
        C:/Users/gcsti/Downloads/NitroSniperGo-master/NitroSniperGo-master/sniper.go:506 +0x159

**Comment by andersfylling** [comment]
Also related: https://github.com/Vedza/NitroSniperGo/issues/303

This is the function that causes the error: https://github.com/andersfylling/disgord/blob/eb6ddbbd10e63349d36c9185c9a3dccfdc81e7be/internal/gateway/client.go#L246

**Comment by csirkepipi** [comment]
Hi, could u fix it, as this is your library? Or how could i?

Anders Øen Fylling ***@***.***> ezt írta (időpont: 2021. jún.
7., H 13:01):

**Comment by andersfylling** [comment]
PR has been created with the patch. It will however, be up to the author of NitroSniperGo to update the disgord reference to the latest once merged.

**Comment by Vedza** [comment]
yeah I'll update it later, Thanks !

**Comment by csirkepipi** [comment]
I just need to do: go get and disgord git link, dont i?

Anders Øen Fylling ***@***.***> ezt írta (időpont: 2021. jún.
7., H 13:10):

**Comment by csirkepipi** [comment]
U alr committed it didnt u?

Quentin ***@***.***> ezt írta (időpont: 2021. jún. 7., H
13:11):

**Comment by andersfylling** [comment]
Merged! No new release yet as there are some details I'm working out. Note that the cache was rewritten, but the API unchanged.

**Comment by csirkepipi** [comment]
Oh ok, when do i expect the update?

Anders Øen Fylling ***@***.***> ezt írta (időpont: 2021. jún.
7., H 13:20):

**Comment by Vedza** [comment]
today

**Comment by csirkepipi** [comment]
Ok :)

Quentin ***@***.***> ezt írta (időpont: 2021. jún. 7., H
13:22):

**Comment by csirkepipi** [comment]
Do u just make a py code like when a new commit is available it runs the go
get code?

Gergely Gombai ***@***.***> ezt írta (időpont: 2021. jún. 7.,
H 13:26):

**Comment by csirkepipi** [comment]
Hm?

Gergely Gombai ***@***.***> ezt írta (időpont: 2021. jún. 7.,
H 13:27):

**Comment by Vedza** [comment]
No, I'm going to use a forked version

**Comment by csirkepipi** [comment]
No, i mean, i just make a py file to automatically pull the git on every
commit, so i keep it updated?

Quentin ***@***.***> ezt írta (időpont: 2021. jún. 7., H
13:44):

**Comment by Vedza** [comment]
You do whatever you want.
I told you on discord I'll use a fork that autoupdate itself.
And will do new release when needed

**Comment by andersfylling** [comment]
Why do you use a fork instead of specifying the disgord version in go.mod?

**Comment by Vedza** [comment]
Because you don't accept self bots

**Comment by csirkepipi** [comment]
What do you mean?

Quentin ***@***.***> ezt írta (időpont: 2021. jún. 7., H
14:09):

**Comment by csirkepipi** [comment]
?

Anders Øen Fylling ***@***.***> ezt írta (időpont: 2021. jún.
7., H 14:08):

**Comment by csirkepipi** [comment]
Ohh like ir pulls it self?

Anders Øen Fylling ***@***.***> ezt írta (időpont: 2021. jún.
7., H 14:08):

**Comment by andersfylling** [comment]
Oh I see @Vedza. Just out of curiosity, what feature is it that you require that a bot can't provide?

**Comment by Vedza** [comment]
This small program automatically claims nitro gift link sent by others users in user's guilds.
So it cannot be a bot, it has to be a real user.

**Comment by csirkepipi** [comment]
Yours dont allow selfbots - he said

Anders Øen Fylling ***@***.***> ezt írta (időpont: 2021. jún.
7., H 14:39):

**Comment by csirkepipi** [comment]
@andersfylling my code, at that line, looks like this:
	nr := c.logSequence.Add(1)
	s := "s:" + strconv.FormatUint(nr, 10)
	shardID := "shard:" + strconv.FormatUint(uint64(c.ShardID), 10)

**Comment by andersfylling** [comment]
Yes, your disgord dependency is outdated, as mentioned earlier. Disgord, develop branch, has the latest patch, but you should see the changes when Vedza has updated his codebase as he mentioned.

**Comment by csirkepipi** [comment]
ok, i think, he will just refork the branch again, and allow selfbot..

**Comment by csirkepipi** [comment]
@Vedza

**Comment by csirkepipi** [comment]
> Yes, your disgord dependency is outdated, as mentioned earlier. Disgord, develop branch, has the latest patch, but you should see the changes when Vedza has updated his codebase as he mentioned.

but wait, if the fork is old, then what was the error at me? like, it could not be that line, could it?

**Comment by csirkepipi** [comment]
i mean, it could not be the exact error, that u fixed

**Comment by csirkepipi** [comment]
@andersfylling I reran the code, in its main go version(1.14) and got this now:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x40211c]

goroutine 21 [running]:
runtime/internal/atomic.Xadd64(0x14e3a114, 0x1, 0x0, 0x916064, 0x1)
        c:/go/src/runtime/internal/atomic/asm_386.s:105 +0xc
go.uber.org/atomic.(*Uint64).Add(...)
        C:/Users/gcsti/go/pkg/mod/go.uber.org/atomic@v1.5.1/atomic.go:190
github.com/andersfylling/disgord/internal/gateway.(*client).getLogPrefix(0x14e3a000, 0x0, 0x11c06fd0)
        C:/Users/gcsti/Downloads/NitroSniperGo-master/NitroSniperGo-master/disgord@custom/internal/gateway/client.go:256 +0xa1
github.com/andersfylling/disgord/internal/gateway.(*client).reconnectLoop(0x14e3a000, 0x14e086e0, 0x11c39cd4)
        C:/Users/gcsti/Downloads/NitroSniperGo-master/NitroSniperGo-master/disgord@custom/internal/gateway/client.go:331 +0x34
github.com/andersfylling/disgord/internal/gateway.(*shardMngr).Connect(0x14e30000, 0x0, 0x0)
        C:/Users/gcsti/Downloads/NitroSniperGo-master/NitroSniperGo-master/disgord@custom/internal/gateway/sharding.go:323 +0xe1
github.com/andersfylling/disgord.(*Client).Connect(0x11d00000, 0x9d8760, 0x11c10038, 0x76a088, 0x11c54820)
        C:/Users/gcsti/Downloads/NitroSniperGo-master/NitroSniperGo-master/disgord@custom/client.go:436 +0x384
github.com/andersfylling/disgord.(*Client).StayConnectedUntilInterrupted(0x11d00000, 0x9d8760, 0x11c10038, 0x11d041e0, 0x0)
        C:/Users/gcsti/Downloads/NitroSniperGo-master/NitroSniperGo-master/disgord@custom/client.go:492 +0x59
main.main.func1.2(0x11d00000, 0x9d8760, 0x11c10038)
        C:/Users/gcsti/Downloads/NitroSniperGo-master/NitroSniperGo-master/sniper.go:631 +0x35
main.main.func1(0x0, 0x0, 0x11c06f88)
        C:/Users/gcsti/Downloads/NitroSniperGo-master/NitroSniperGo-master/sniper.go:656 +0x41a
created by main.main
        C:/Users/gcsti/Downloads/NitroSniperGo-master/NitroSniperGo-master/sniper.go:583 +0x157

**Comment by csirkepipi** [comment]
and also, you said that is a prob with "arm" but i have an x86_64 cpu

**Comment by csirkepipi** [comment]
i reran the code several times and i got this:

16:29:05 [x] Error creating Discord session for OddBdRjQ1JBLLiz0CiSvGc, You are being rate limited.
{
  "global": false,
  "message": "You are being rate limited.",
  "retry_after": 2974
}

GET:/gateway/bot => [GET:/gateway/bot]
16:29:05 [x] Error creating Discord session for ODMyNzI5ODgdBdRjQ1JBLLiz0CiSvGc, You are being rate limited.
{
  "global": false,
  "message": "You are being rate limited.",
  "retry_after": 2828
}

GET:/gateway/bot => [GET:/gateway/bot]
Sniping Discord Nitro and Giveaway on 0 servers and 1 accounts 🔫

16:29:05 [+] Sniper is ready

ALTHOUGH i was not ratelimited @andersfylling

**Comment by csirkepipi** [comment]
or @Vedza idk which of you has this ratelimit part.

**Comment by andersfylling** [comment]
Rate limiting errors are expected. Discord gives you bucket ids eventually so you can group endpoints/calls and do proper rate limiting. 

The error message is the same as before.

**Comment by csirkepipi** [comment]
@andersfylling Vedza has a lots of work with one of his projects, and does not rly have time to fix this, how could i fix it on my own, cuz as it is a really really old fork, i dont really know..
#fukdiscordapiupdate

**Comment by andersfylling** [comment]
Vedza can give you instructions on this. I don't support self bots as they are against Discord TOS.

**Comment by Vedza** [comment]
Went back to an old discordgo update, It was easier for me as the sniper was originally made for that library and I found an old version that still works with self bot. But thanks for the fix @andersfylling 🙏
