### ISSUE TITLE
Deploy to heroku having issues

### ISSUE THREAD

**Issue by ibndiaye** [Vedza/NitroSniperGo#323]
Hello, when i deploy the app to heroku i get this error:
`No app.json located in the repo URL provided. `
![image](https://user-images.githubusercontent.com/63436162/121230736-e9017f00-c88f-11eb-8dff-932593de7a71.png)

**Comment by Vedza** [comment]
Hi,
Did you click on the readme link ?

**Comment by ibndiaye** [comment]
> 
> 
> Hi,
> Did you click on the readme link ?

Yeah i did

**Comment by Vedza** [comment]
Can you check that your url is `https://heroku.com/deploy?template=https://github.com/Vedza/NitroSniperGo/tree/heroku`,  maybe it redirects you 🤔

**Comment by ibndiaye** [comment]
> 
> 
> Can you check that your url is `https://heroku.com/deploy?template=https://github.com/Vedza/NitroSniperGo/tree/heroku`, maybe it redirects you 🤔

This is my url when i press on the deploy button: `https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2FVedza%2FNitroSniperGo&template=https%3A%2F%2Fgithub.com%2FVedza%2FNitroSniperGo%2Ftree%2Fheroku`

When i press on your link i get the same error

**Comment by Vedza** [comment]
I'm sorry but I don't know why you have that error. It's working for me even if I copy your url

**Comment by ibndiaye** [comment]
Ill try another browser since the current one im using has a lot of extensions and userscripts

**Comment by ibndiaye** [comment]
Yep it worked on a different browser, thanks for the help!
