### ISSUE TITLE
Console Spam with Error

### ISSUE THREAD

**Issue by killer124453453453457** [Vedza/NitroSniperGo#324]
hello, I have run my nitrosniper at heroku, every time I start it, it spams a error:
"[DG0] wsapi.go:551:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string"

could that get fixxed or what I do false?

**Comment by Vedza** [comment]
https://github.com/Vedza/NitroSniperGo#known-issues
