### ISSUE TITLE
Weird Error "Payment source required to redeem gift"

### ISSUE THREAD

**Issue by NamNam0w0** [Vedza/NitroSniperGo#327]
I have never gotten this error until now, and it seems alts are causing the issue, but I'm not sure why ? I tried replacing the tokens, and it's not working either... what does this error mean?

**Comment by Vedza** [comment]
You have to add a payment method on your main account

**Comment by NamNam0w0** [comment]
But why do I have to do this now and never before have I had to do that? Im sorry but I am feeling pretty sus about that.

**Comment by Wolfkid200444** [comment]
This error only happens because you had nitro before in your account this code is only for those who had not redeem nitro before (promo with epicgames and discord)

**Comment by NamNam0w0** [comment]
I'm confused, sorry. Do you mean because I have nitro right now and because epicgames is doing a giveaway that I may not be able to redeem it without having a payment method ??

**Comment by Vedza** [comment]
That's just how Discord work. If you try to redeem a lots of Nitro they ask you to put a payment method to redeem one
