### ISSUE TITLE
sniper.go not working

### ISSUE THREAD

**Issue by Rayyan2650** [Vedza/NitroSniperGo#33]
i entered the token in the setting.json but when I click the sniper.go this shows up
![image](https://user-images.githubusercontent.com/59572861/97084078-dfdbde80-162d-11eb-9dcb-7ba8ceb7adfa.png)

**Comment by Vedza** [comment]
This is because you downloaded source files and need to compile it before running it. But I already made it for you, you can download the executable [here](https://github.com/Vedza/NitroSniperGo/releases/tag/v1.2)
