### ISSUE TITLE
What exactly is cooldown?

### ISSUE THREAD

**Issue by Superbulzo** [Vedza/NitroSniperGo#330]
Like, if i snipe a nitro there is a cooldown to snipe another one?

**Comment by Vedza** [comment]
Yes

**Comment by Superbulzo** [comment]
dude
it isn't working

**Comment by Vedza** [comment]
It should wait `x` hours after it redeemed a Nitro, not just tried to claim one.

**Comment by Superbulzo** [comment]
no, the sniper is not workin

**Comment by Superbulzo** [comment]
it doesent' join gw
