### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by luca2k19ro** [Vedza/NitroSniperGo#338]
**Describe the bug**
ok so after opening the program it shows me up 2 times the error: 2021/06/13 22:34:19 [DG0] wsapi.go:551:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string

**Expected behavior**
i would like to mention that i disabled giveaway, invite and privnote

**Screenshots**
![image] (https://user-images.githubusercontent.com/75110924/121819902-5c443000-cc98-11eb-9924-f33cb3ae4d29.png)

**Comment by skhrlx** [comment]
I'm getting this same error too =/

**Comment by Vedza** [comment]
https://github.com/Vedza/NitroSniperGo#known-issues
