### ISSUE TITLE
Not claiming 

### ISSUE THREAD

**Issue by carterdacat** [Vedza/NitroSniperGo#34]
Hi, ive had this running for about a day and a half, and almost 50 have gone by, it saying already claimed. When I start the bot, it errors, but it didn’t look problematic. Any ideas? (Btw the token is meant to start with mfa. right?)

**Comment by Vedza** [comment]
Hi, yes this is your token and yes it's working as it should be. But it's really hard to get nitro cause a lot of people have nitro sniper now. It can take a few days to a few weeks to get your first nitro. The best servers I got was ones where there isn't a lot of people, and as you get the fastest nitro you claim them first. I recommend joining little servers, even if there is a drop once in a week, it's still better than 5 a days with other 200 nitro snipers in it.
