### ISSUE TITLE
Payment source needed?

### ISSUE THREAD

**Issue by sxoxo** [Vedza/NitroSniperGo#347]
I've had the sniper for a while now, and for the first week it was just invalid codes, then I started getting a shit ton of hits but none of them work because the sniper says "Payment source needed" or something like that, forgot what it was cause I haven't used the program in a bit. Not sure if I actually need to link a card to my discord (which doesn't make any sense as I can redeem any other code without a card) or if it's just a bug.

**Comment by kamikazeghost** [comment]
had that problem, added card. now i get verification errors

**Comment by Vedza** [comment]
Discord issue, you need to add a payment method and verify your account to claim Nitro gift.
