### ISSUE TITLE
Payment source needed to redeem

### ISSUE THREAD

**Issue by xxJustin562xx** [Vedza/NitroSniperGo#353]
Why does it keep saying that? Both my alt and main already have a payment source added and it still says that. Am I doing something wrong?

**Comment by Zenixas** [comment]
I'm getting the same thing, I believe it happens when it tries to snipe the Epic Games nitro, instead of a normal gift. Atleast then is when this problem started for me.

**Comment by xxJustin562xx** [comment]
does it even auto claim? It’s been 3 days and all it says is payment source required and that’s about it.

**Comment by xxJustin562xx** [comment]
Nvm, now it says “Authentication Required”
