### ISSUE TITLE
Why it says Authentication required error

### ISSUE THREAD

**Issue by kamikazeghost** [Vedza/NitroSniperGo#359]
This isn't a bug report its more of a statement.

The reasoning behind the error "Authentication required" is the sniper trying to claim the 3 month codes with or without credit card info connected to your account it cannot be claimed with an active sub to nitro.

![image](https://user-images.githubusercontent.com/72900687/126026006-ceeb9462-e200-4ad3-8775-d295127c71b6.png)
![image](https://user-images.githubusercontent.com/72900687/126026081-656068c1-f118-4d78-a131-49d074517a3d.png)

**Comment by 3w7** [comment]
it is a problem on discord backend/server since it is trying to take 1$ as verification for claim it
