### ISSUE TITLE
Cannot check gift validity.

### ISSUE THREAD

**Issue by carterdacat** [Vedza/NitroSniperGo#36]
Im getting these on 99% of codes the bot see. What does this mean?

**Comment by carterdacat** [comment]
I've looked thought the code, and noted how the logger works. I saw that the default (if it's not rejected or accepted) is what I'm getting. I've tried to send the api request as well, and I have been getting 405 errors (not 100% sure I'm doing it right though). Umm not a go programmer (js is what I do), so I wana hear what your thoughts are

**Comment by SploeCyber** [comment]
> Im getting these on 99% of codes the bot see. What does this mean?

same

**Comment by Vedza** [comment]
Hi, this happens when discord api return nothing. I believe It happens when the gift is a game. Check on your library if you have new games.

**Comment by Vedza** [comment]
Or maybe discord just added a new security that don't return anything if you make too much request on redeem endpoint

**Comment by carterdacat** [comment]
> Hi, this happens when discord api return nothing. I believe It happens when the gift is a game. Check on your library if you have new games. 

I checked one of them, (and saw it be shown) and it was a nitro classic

**Comment by carterdacat** [comment]
I'll check tho

**Comment by Vedza** [comment]
You can change
```go
color.Yellow("[-] Cannot check gift validity")
```
to
```go
color.Yellow(bodyString)
```
To see the exact api response

**Comment by carterdacat** [comment]
Ok, I'll try that rq

**Comment by 7lq** [comment]
most of these codes are **Xbox GamePass** or discordGames, is normal

**Comment by lookeey** [comment]
Also, there are some glitched codes that display not claimed, but once you click they say it's already claimed. Those codes return `Cannot check gift validity` in the console as well.

**Comment by Vedza** [comment]
This is the same issue, but I can't do anything as it comes from discord api. So as @7lq said it's either games or rate limit

**Comment by carterdacat** [comment]
@Vedza After 3 days I got a message. It says "payment source required to redeem gift" with a 50070 code

**Comment by carterdacat** [comment]
Attempting to fix payment, even though it's fine

**Comment by carterdacat** [comment]
@Vedza hmmm I keep getting payment source required, but I have my PayPal linked. Weird

**Comment by Vedza** [comment]
I can't do anything as it comes from Discord API, I think there is an other endpoint to redeem code. I'll check this week but the result might be the same

**Comment by carterdacat** [comment]
Ok. I'll ask on the api server as well

**Comment by noto-rious** [comment]
> 
> 
> I can't do anything as it comes from Discord API, I think there is an other endpoint to redeem code. I'll check this week but the result might be the same

Same endpoint different version number, I have unofficially forked this project and updated the API if you care to take a look.

**Comment by NotSwaraj** [comment]
If you get payment required thing it means the code is glitched. it cant be redeemed by anyone else either. Also the api is crap sometimes eg : the ratelimits never end lol anyways good luck!

**Comment by nions-ops** [comment]
Is it a glitch or an anti-sniping feature? Pretty sure it's the latter, since that API response has been up since November. I don't think it's bugged though.

**Comment by nions-ops** [comment]
> @Vedza hmmm I keep getting payment source required, but I have my PayPal linked. Weird

Same here. Paylink + Card linked and still getting it.....

**Comment by nions-ops** [comment]
@Vedza Seems like this issue makes snipers unusable....

Either like the other guy said, ratelimits are absolute shit or Discord just found a new way to fuck with sniping. Even doing what it says by adding a payment source doesn't solve the issue.

**Comment by NotSwaraj** [comment]
> @Vedza Seems like this issue makes snipers unusable....
> 
> Either like the other guy said, ratelimits are absolute shit or Discord just found a new way to fuck with sniping. Even doing what it says by adding a payment source doesn't solve the issue.

Hey @nions-ops 

After some research I have figured out that this is NOT api problems or anything. instead it is with discord;

What does this mean?
You may know the xbox nitro event where you could buy nitro codes for like a dollar, Now what smart people did to mess with sniping is taking the xbox gift code and add discord.gift/ in front of it, no one can claim these no matter what, even if they click claim in channel! Hope that answers your question.

**Comment by Vedza** [comment]
I just updated the api and did some tests and had the "payment source required" the first time with Nitro code, so I put the payment source id manually in the request and got "New subscription required to redeem gift". Maybe you cannot have more than 1 month of Nitro gift, I don't really know. I'll close the issue as I think we can't do anything. You can still update to the latest version to see the exact error and if you get different errors or understand what is happening feel free to tell us here.
