### ISSUE TITLE
Release the program for Linux

### ISSUE THREAD

**Issue by alext30Developer** [Vedza/NitroSniperGo#361]
I know there's already the Nitro Sniper made in Python. However, I would like the new and improved version to be available for Linux directly. As of right now, I managed to get the program working using Wine.

**Comment by 3w7** [comment]
u can build itself by running this on your bash/terminal
```
git clone https://github.com/Vedza/NitroSniperGo.git
cd NitroSniperGo
go mod download
go mod build
./NitroSniperGo
```

**Comment by 3w7** [comment]
or you can download this build:
https://cdn.discordapp.com/attachments/867507412349222976/868321706681454632/NitroSniperGo_build_linux.zip (always check virustotal or hybrid scan)

**Comment by alext30Developer** [comment]
Thanks!
