### ISSUE TITLE
What does This gift has been redeemed already?

### ISSUE THREAD

**Issue by tzt345** [Vedza/NitroSniperGo#365]
↑↑↑

**Comment by Vedza** [comment]
It actually means the gift has been redeemed already. (just ignore it)

**Comment by tzt345** [comment]
> It actually means the gift has been redeemed already. (just ignore it)

K tnks :D & btw tnks for this tool!

**Comment by Vedza** [comment]
When you have more than 1 month of Nitro it will put it in account credit 
<img width="685" alt="Capture d’écran 2021-07-28 à 17 15 45" src="https://user-images.githubusercontent.com/28839427/127348611-c1ca449c-1b9b-40fb-8cda-88cd4a755426.png">

**Comment by tzt345** [comment]
@Vedza

**Comment by tzt345** [comment]
Can you give me a legit nitro servers?

Cuz u have a lot of nitro :0

**Comment by tzt345** [comment]
> When you have more than 1 month of Nitro it will put it in account credit
> <img alt="Capture d’écran 2021-07-28 à 17 15 45" width="685" src="https://user-images.githubusercontent.com/28839427/127348611-c1ca449c-1b9b-40fb-8cda-88cd4a755426.png">

Give me a legit nitro servers that ur in plz
