### ISSUE TITLE
Suggestion Can you make it quicker I know this is a lot to ask

### ISSUE THREAD

**Issue by MD211211** [Vedza/NitroSniperGo#368]
I’m just saying because every time somone sends out nitro another sniper snipes it before me

**Comment by MD211211** [comment]
I know this is a lot to ask but it’s just a suggestion and if you can’t do this it’s totally fine 
It’s still really good thou

**Comment by MD211211** [comment]
And a lot of people sniped before me

**Comment by bytixo** [comment]
If you had any coding experience as you said, you will know that this has nothing to do with the program itself.

**Comment by Zenixas** [comment]
"have coding experience" - than might as well make it faster yourself??

**Comment by MD211211** [comment]
I’m bad at coding thou

**Comment by TomerGamerTV** [comment]
> > If you had any coding experience as you said, you will know that this has nothing to do with the program itself.
> 
> Yeah this is Heroku's problem the ping is bottlenecking the sniper.

and if I'm running it on my PC?
