### ISSUE TITLE
Nitro Sniper stopped for some reason

### ISSUE THREAD

**Issue by felixvonderladen** [Vedza/NitroSniperGo#369]
For some reason the Nitro Sniper stopped working and I don't know why. Everything worked fine, but now nothing is being detected except the only thing it recognizes are my own messages as an example when I send a fake Discord Nitro gift message in a channel. I know the reason could be that no one is typing a code in a chat, but I find this very unlikely because there were 90 attempts to redeem a code every day and I even got 4 months of nitro and now it just stopped . I tried the tokens and they all worked but for some reason no codes are recognized :(

**Comment by b1ank3r** [comment]
There are paid sniper, you ain't gonna win against them.
