### ISSUE TITLE
[CRASH/BUG] - When snipped program just quits

### ISSUE THREAD

**Issue by Sehyn** [Vedza/NitroSniperGo#394]
Hey, that simple.

I've been snipping two successfully, thanks to you they were added to my account and everything.
But I found out that the program just closes once it's successfully sniped.
I doubt this is normal right?
Thanks though you saved me 20$ :).

EDIT: Checked previous issues: https://github.com/Vedza/NitroSniperGo/issues/372

I don't see though where's it says anything about it ? Sorry If i'am too blind to see it.

Cause, the tokens doesn't change as I start back the Sniper with same token and I'm back at sniping again.

**Comment by Vedza** [comment]
Duplicate

**Comment by Sehyn** [comment]
Bah frère donnes le motif non?

**Comment by Vedza** [comment]
C'est un bug à corriger c'est tout.

**Comment by Sehyn** [comment]
Bah je pense que mon issue a correctement été rempli, donc j'attendais une réponse un plus précise du pourquoi du comment et où ça survient pour pouvoir le corriger moi même c'est pas comme si j'ai mis "not working after sniping fix the pls" j'ai même cherché dans les autres issues mais bon bref.
Merci quand même.

**Comment by Vedza** [comment]
Oui justement tu peux rien faire en fait, c'est un bug à la récupération du message après un sniping. Le problème c'est que je travail plus sur ce projet  depuis très longtemps (Je suis en train de fermer les issues pour archiver le projet) et pour débugger il faudrait que je snipe un code pour voir exactement où ça plante, ou alors que quelqu'un me donne le log exact quand ça crash. Et actuellement j'ai aucun intérêt à faire ça désolé.
