### ISSUE TITLE
Please give me an invite to the paid sniper

### ISSUE THREAD

**Issue by inverspe** [Vedza/NitroSniperGo#399]
Im interested

**Comment by Swordifyy** [comment]
have you heard back about this? Im interested too.

**Comment by slowwdev** [comment]
bruh the server to buy the paid sniper has been termed lmao

**Comment by Swordifyy** [comment]
> bruh the server to buy the paid sniper has been termed lmao

slow, whats your discord? i wanna ask u something

**Comment by Ender786** [comment]
@inverspe @Swordifyy Vedza is no longer the dev for it, it was sold to someone else and they have continued you it, you can join their telegram which is https://t.me/Genefit

**Comment by slowwdev** [comment]
> @inverspe @Swordifyy Vedza is no longer the dev for it, it was sold to someone else and they have continued it, you can join their telegram which is https://t.me/Genefit
> 
> The website is https://genefit.cc/

bruh why are you telling them the website, i was asking for money them lmfao

**Comment by Ender786** [comment]
> > @inverspe @Swordifyy Vedza is no longer the dev for it, it was sold to someone else and they have continued it, you can join their telegram which is https://t.me/Genefit
> > The website is https://genefit.cc/
> 
> bruh why are you telling them the website, i was asking them for money lmfao

because I'm not a dick like you, how desperate are you for money

**Comment by Swordifyy** [comment]
> 

Thank you so much! I really appreciate it.

**Comment by Vedza** [comment]
Guys just invest on a basic VPS in North Virginia and use this sniper if you just want Nitro. The paid one is slightly faster but maybe 15% faster while the vps location can divide the delay by 2 or 3 if you have quite bad internet connection.
