### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LudovicoSforza** [Vedza/NitroSniperGo#401]
So, I've been using this for like 2 months. and I always get this error. Was it really someone who was faster than me?
![image](https://user-images.githubusercontent.com/44255157/147328074-0eaa17cc-da0d-4a30-b51a-48de9e17f92e.png)

**Comment by slowwdev** [comment]
> So, I've been using this for like 2 months. and I always get this error. Was it really someone who was faster than me? ![image](https://user-images.githubusercontent.com/44255157/147328074-0eaa17cc-da0d-4a30-b51a-48de9e17f92e.png)

lmfao its just people who drops already claimed nitro

**Comment by LudovicoSforza** [comment]
i finally got 1 after changing my payment method 🤣
