### ISSUE TITLE
Can run for 24/7 anymore on Hekoru.

### ISSUE THREAD

**Issue by weezyblesam** [Vedza/NitroSniperGo#403]
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy. 

Any fix to this?

**Comment by josesilveiraa** [comment]
Fork it

**Comment by weezyblesam** [comment]
> Fork it

how do i do that?

**Comment by inverspe** [comment]
> Fork it

I forked it and clicked deploy to heroku still doesnt work

**Comment by Reware53** [comment]
> > Fork it
> 
> I forked it and clicked deploy to heroku still doesnt work

fork it with **/tree/heroku** in the end like this: 
https://dashboard.heroku.com/new?template=https://github.com/ReWare53/NitroSniperGo/tree/heroku

**Comment by inverspe** [comment]
> > > Fork it
> > 
> > 
> > I forked it and clicked deploy to heroku still doesnt work
> 
> fork it with **/tree/heroku** in the end like this: https://dashboard.heroku.com/new?template=https://github.com/ReWare53/NitroSniperGo/tree/heroku

Thanks man

**Comment by josesilveiraa** [comment]
> > > Fork it
> > 
> > I forked it and clicked deploy to heroku still doesnt work
> 
> fork it with **/tree/heroku** in the end like this: 
> https://dashboard.heroku.com/new?template=https://github.com/ReWare53/NitroSniperGo/tree/heroku
> 
> 

he copin' for real
