### ISSUE TITLE
[x] Failed to parse JSON file:  invalid character '"' after array element

### ISSUE THREAD

**Issue by Lumi6x9** [Vedza/NitroSniperGo#404]
**Please check previous issues before opening a new one as well as [Know Issues](https://github.com/Vedza/NitroSniperGo#known-issues)**

**Describe the bug**
[x] Failed to parse JSON file:  invalid character '"' after array element

**To Reproduce**
1. Go to 'folder'
2. Configure 'setting.json'
3. Run "exe" file

**Expected behavior**
It shows showcase

**Screenshots**
![image](https://user-images.githubusercontent.com/92018454/148536190-75e93d20-0302-4011-917a-0ce46a3671f2.png)
![image](https://user-images.githubusercontent.com/92018454/148536227-c173a10b-d4f2-4aed-a446-3ddb881391d2.png)

**Additional context**
Tell me way to fix it pls

**Comment by Lumi6x9** [comment]
{
  "tokens": {
    "main": "i filled it already",
    "alts": [
      ""
    ]
  },
  "status": {
    "main": "dnd",
    "alts": "invisible"
  },
  "nitro": {
    "max": 2,
    "cooldown": 24,
    "main_sniper": false,
    "delay": true
  },
  "giveaway": {
    "enable": true,
    "delay": 15,
    "dm": "Gura is here!",
    "dm_delay": 8,
    "blacklist_words": [
      "bot",
      "test",
      "ban"
      "auto"
      "dont"
      "react"
    ],
    "whitelist_words": [
      "nitro"
    ],
    "blacklist_servers": []
  },
  "invite": {
    "enable": true,
    "delay": {
      "min": 2,
      "max": 10
    },
    "max": 10,
    "cooldown": 6
  },
  "privnote": {
    "enable": false
  },
  "webhook": {
    "url": "i filled it already",
    "good_only": false
  },
  "blacklist_servers": []
}

**Comment by Lumi6x9** [comment]
its my settings

**Comment by Janisbtw** [comment]
You forgot a few commas at `"blacklist_words": [
"bot",
"test",
"ban"
"auto"
"dont"
"react"
],`

replace it with the following and it should work:
`"blacklist_words": [
"bot",
"test",
"ban",
"auto",
"dont",
"react"
],`
