### ISSUE TITLE
Is there a way to run NitroSniperGo on a 32 bit pc?

### ISSUE THREAD

**Issue by weezyblesam** [Vedza/NitroSniperGo#405]
is there a way to run NitroSniperGo on chrome? my heroku ran out of free hours so im planning to use my netbook and let it run for 24 hours instead. i dont wanna risk my gaming pc being on for that long.

**Comment by inverspe** [comment]
make a new gmail account then register a new heroku account

**Comment by weezyblesam** [comment]
> make a new gmail account then register a new heroku account

I tried making a new account but it said, We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

**Comment by Vedza** [comment]
Follow the compilation instructions and it will work
