### ISSUE TITLE
exported var Token should have comment or be unexported

### ISSUE THREAD

**Issue by dsogo** [Vedza/NitroSniperGo#42]
![image](https://user-images.githubusercontent.com/60483946/99199474-2d0b2600-277e-11eb-9dfe-11384c7745cd.png)

**Comment by Vedza** [comment]
This is just a lint warning, I don't know what you want me to do with that. Do you want me to comment my code so people can understand it (even if token is pretty explicit) or do you just don't understand this warning ?

**Comment by dsogo** [comment]
I don't really understand go so I thought it best to ask

**Comment by Vedza** [comment]
Ok np, it's just a warning about linting so it's not important
