### ISSUE TITLE
Receiving "Response 401: Unauthorized"

### ISSUE THREAD

**Issue by nrxzc** [Vedza/NitroSniperGo#420]
For the past few moths the sniper worked great, though a couple weeks ago I started getting these responses. 
![Discord_UzpNC8n7Pb](https://user-images.githubusercontent.com/46836521/151651781-cab2180d-e94e-4777-8a6d-fe2677f5d129.png)
any reason why its doing this?

**Comment by Mewzax** [comment]
> For the past few moths the sniper worked great, though a couple weeks ago I started getting these responses. ![Discord_UzpNC8n7Pb](https://user-images.githubusercontent.com/46836521/151651781-cab2180d-e94e-4777-8a6d-fe2677f5d129.png) any reason why its doing this?

It looks like Discord added a security feature where your token change every time but also expire with 2FA, that might be the reason why the sniper doesn't work after some time or if you get an unauthorized error when sniping Nitro


So just change your discord password and reget your token
