### ISSUE TITLE
Item Could not be created on Heroku

### ISSUE THREAD

**Issue by XxGhost280xX** [Vedza/NitroSniperGo#421]
I think that Heroku have blacklisted this source code.
![image](https://user-images.githubusercontent.com/81826119/152649292-cb28683b-e769-4e66-9c33-91d4fd6e890e.png)
![image](https://user-images.githubusercontent.com/81826119/152649337-a7b1def9-b549-4373-8456-e7b49f526eb6.png)

**Comment by Vedza** [comment]
https://github.com/Vedza/NitroSniperGo/discussions/417
