### ISSUE TITLE
just opens and closes instantly 

### ISSUE THREAD

**Issue by bruhmomentoxd** [Vedza/NitroSniperGo#45]
cant seem to open it dunno why no errors show up

**Comment by Vedza** [comment]
Hi, Your token is probably not working or you didn't put any in settings.json

**Comment by bruhmomentoxd** [comment]
dunno i have done all of the steps

**Comment by bruhmomentoxd** [comment]
![Uploading Screenshot 2020-11-24 163231.png…]()

**Comment by bruhmomentoxd** [comment]
fixed it token was wrong weird
