### ISSUE TITLE
Disable Giveaway Message

### ISSUE THREAD

**Issue by HZ-0Z3R0** [Vedza/NitroSniperGo#47]
Hi, I've been using NitroSniper for some time and it works very well! However, I will automatically send a message to the giveaway hoster, which I don't want. How can I disable that?

**Comment by Vedza** [comment]
Hi, You can remove line 296 but I'll add this options in settings tonight.

**Comment by Vedza** [comment]
Done ccf6b21541db4f2db283299b651718379733caef
