### ISSUE TITLE
As soon as app opens Unmarshalling error

### ISSUE THREAD

**Issue by synsmasher** [Vedza/NitroSniperGo#48]
2020/11/29 21:20:27 [DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string

**Comment by Vedza** [comment]
#2 #6 #32 
> Hi, it comes from a library I use because we're using a token that doesn't come from a bot. Some people have it and some not, but the program works fine even with this error.
