### ISSUE TITLE
./NitroSniperGo how do i use this

### ISSUE THREAD

**Issue by macaron1405** [Vedza/NitroSniperGo#53]
this is probably going to make me look stupid but when i typed ./NitroSniperGo into command prompt its came back with an error ('.' is not recognized as an internal or external command, operable program or batch file.) the other commands worked fine

**Comment by macaron1405** [comment]
it also says "2020/12/22 10:20:54 [DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string" when i start it up

**Comment by Vedza** [comment]
Hi, it seems you managed to run it. don't worry about this error, it's working fine
