### ISSUE TITLE
Some Error

### ISSUE THREAD

**Issue by bBSempai** [Vedza/NitroSniperGo#55]
what is this error and how do I fix it thankyou
![image](https://user-images.githubusercontent.com/64588227/103128156-25fb0000-46ba-11eb-8c00-22c815bb40e1.png)

**Comment by rednek46** [comment]
Don't mind it, the sniper still works fine.
#49

**Comment by Vedza** [comment]
I hide this error in the last version but yeah it wasn't a problem.
