### ISSUE TITLE
Webhook Support

### ISSUE THREAD

**Issue by hairyfred** [Vedza/NitroSniperGo#60]
Allows you to add a webhook
Usefull to know if its sniped anything on alt accounts

**Comment by Vedza** [comment]
Good idea, I'll add this soon !

**Comment by Vedza** [comment]
Done ec57ce5 !

**Comment by hairyfred** [comment]
Add an option to only interact with the webhook when you win a giverway/snipe valid nitro

**Comment by Vedza** [comment]
done e45060c
