### ISSUE TITLE
[Suggestions] Alt Tokens, Heroku, Display Speed

### ISSUE THREAD

**Issue by Aokiare** [Vedza/NitroSniperGo#61]
1. add multiple tokens support, for example snipping on alt accounts but claiming on main account
2. make the app deployable through Heroku so its ensured that it is running all the time and probably faster than self hosted
3. not that important but display how fast (ms) the operation took, whether it claimed a code or not
thank you!

**Comment by brams1441** [comment]
I totally would love these features!!

**Comment by Vedza** [comment]
Hey, thanks for your suggestions.
I just added Heroku button !
I could add delay if you really want it but as I said a few times this will make the sniper (a little) slower.
And about the alt account, I've never added this feature cause first I didn't need it to get Nitro but also because this might make your account banned because of too many requests made.

**Comment by brams1441** [comment]
@Vedza Hey ive just hosted it on heroku but isnt the dyno type supposed to be worker? 
![image](https://user-images.githubusercontent.com/63436162/103460488-d0a49b80-4d16-11eb-9a20-d3c98c398a1c.png)

**Comment by Vedza** [comment]
Yes you're right, I just made a basic config and saw in the logs it's working, I'm going to check how to change that.

**Comment by brams1441** [comment]
Okay thank you for making and maintaining this awesome sniper!!

**Comment by Vedza** [comment]
np, It's fixed now but you have to manually enable the worker.
 I don't know if I can change that

**Comment by bonxz** [comment]
Bot is Up but in Logs there is a new error. but still running 

`2021-01-02T16:18:17.272634+00:00 app[worker.1]: 2021/01/02 16:18:17 [DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.last_message_id of type string
2021-01-02T16:18:17.293977+00:00 app[worker.1]: `

**Comment by Vedza** [comment]
This error come from discordgo library because we're doing a selfbot. Don't worry, the bot will still work fine

**Comment by irritability** [comment]
Having the issue of the api server?
`API server listening at: 127.0.0.1:20849
error opening connection, websocket: close 4004: Authentication failed.
Process exiting with code: 0
`

**Comment by Vedza** [comment]
Your token is not working

**Comment by Aokiare** [comment]
thank you! closing

**Comment by Vedza** [comment]
I've added some features including alts accounts on branch `v2`, need to do some tests before release but it seems it works.
Btw it would be nice if you guys put a star on my repo 👍

**Comment by Vedza** [comment]
https://github.com/Vedza/NitroSniperGo/tree/v2
