### ISSUE TITLE
Webhook Buggy?

### ISSUE THREAD

**Issue by bonxz** [Vedza/NitroSniperGo#65]
![grafik](https://user-images.githubusercontent.com/61289944/103465888-0e69ea00-4d40-11eb-885a-ce333aacc2ab.png)

No more informations in webhook. Is it supposed to be like this?

**Comment by Vedza** [comment]
Yeah I might have broke something, I'm finishing privnote thing, and I'll check that

**Comment by hairyfred** [comment]
Can also say Ive experienced this but with giverways instead

**Comment by Vedza** [comment]
I think it's fixed on `v2` branch.

**Comment by hairyfred** [comment]
> 
> 
> I think it's fixed on `v2` branch.


Compiled v2 , been running a few hours , no issues yet
