### ISSUE TITLE
[DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string

### ISSUE THREAD

**Issue by MarzBaren** [Vedza/NitroSniperGo#67]
Hm
[DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string

It seems like it doesn't join giveaways. Nitro sniper works fine tho

**Comment by Vedza** [comment]
The error is not a problem.
If it doesn't join giveaway it's because the sniper doesn't work with the bot doing the giveaway

**Comment by MarzBaren** [comment]
Ok, might add the bot myself then

Den man. 4. jan. 2021 kl. 12.34 skrev Quentin <notifications@github.com>:
