### ISSUE TITLE
question

### ISSUE THREAD

**Issue by iRobbedNitreo** [Vedza/NitroSniperGo#72]
can you add more than 2 alt accounts to this ? also whats your discord ?

**Comment by Vedza** [comment]
Hi,
You can add as many token as you want

```
  "alts_tokens": [ // Alts token
    "",  //Token1
    "",  //Token2
    ...
  ]```

And I don't give my discord because I don't want my account banned sorry

**Comment by iRobbedNitreo** [comment]
i had you added brother , i got banned that's why im asking lol

**Comment by Vedza** [comment]
I don't put my discord here but you can give me your discord

**Comment by iRobbedNitreo** [comment]
ok dont worry about it lol , you should add snipers for other things. like bot games etc

**Comment by Vedza** [comment]
I actually don't know much about other discord things to snipe, and I don't have time to add other stuffs from now on :/

**Comment by iRobbedNitreo** [comment]
ok .

**Comment by iRobbedNitreo** [comment]
you able to add a slotbot wallet grabber ? its a game bot that drops wallets and you do ~grab to pick them up

**Comment by iRobbedNitreo** [comment]
?

**Comment by Vedza** [comment]
I don't know this, so I have to understand how it works and what to snipe first. So I won't do this soon

**Comment by iRobbedNitreo** [comment]
it should be simple just scan for this message "Someone just dropped their wallet in this channel! Hurry and pick it up with `~grab` before someone else gets it!" from the ID : 346353957029019648 . then reply with "~grab" .

**Comment by Vedza** [comment]
If it's just that then add 
```go
 else if strings.Contains(m.Content, "Someone just dropped their wallet in this channel! Hurry and pick it up with ~grab before someone else gets it!") && m.Author.ID == "346353957029019648" {
		_, _ = s.ChannelMessageSend(m.ChannelID, "~grab!")
	}
```
after line 599

**Comment by iRobbedNitreo** [comment]
ok i added hopefully it works , thanks

**Comment by Vedza** [comment]
Np, It will work if this is the exact message.
I just edited my last message, so you'll have something printed on the program if this happens.
But be careful because I don't know how fast you have to be but this will be almost instant so if other people see this they might report you

**Comment by iRobbedNitreo** [comment]
else if strings.Contains(m.Content, "Someone just dropped their wallet in this channel! Hurry and pick it up with `~grab` before someone else gets it!") && m.Author.ID == "346353957029019648" {
		_, _ = s.ChannelMessageSend(m.ChannelID, "~grab")
		_, _ = magenta.Print(time.Now().Format("15:04:05 "))
		_, _ = green.Print("[+] Grabbed a wallet ")
		guild, err := s.State.Guild(m.GuildID)
		if err != nil || guild == nil {
			guild, err = s.Guild(m.GuildID)
			if err != nil {
				return
			}
		}

		channel, err := s.State.Channel(m.ChannelID)
		if err != nil || guild == nil {
			channel, err = s.Channel(m.ChannelID)
			if err != nil {
				return
			}
		}
		_, _ = magenta.Println(" [" + guild.Name + " > " + channel.Name + "]")
	}

**Comment by iRobbedNitreo** [comment]
thats how i done it ^

you missed a couple of things and its fine lol . just a server with my friend lol

**Comment by iRobbedNitreo** [comment]
yeah you did lol , but yeah it works thank you
