### ISSUE TITLE
Ghost giverway "Win"

### ISSUE THREAD

**Issue by hairyfred** [Vedza/NitroSniperGo#74]
Again the og message where the "giverway" was is deleted so ghost giverways causing false positives?

**Comment by Vedza** [comment]
I don't understand your issue, but I fixed the false positive giveaway won 2 hours ago.
If you don't have the latest version then download it

**Comment by Vedza** [comment]
Oh maybe you mean the giveaway message is delete when trying to react ?

**Comment by hairyfred** [comment]
> 
> 
> I don't understand your issue, but I fixed the false positive giveaway won 2 hours ago.
> If you don't have the latest version then download it

I built it from source , so im on the latest i can be





> 
> 
> Oh maybe you mean the giveaway message is delete when trying to react ?

It says ive won a giverway in a channel not for giverways ,log into my alt to go look , no message can be found/reaction from the bot

**Comment by hairyfred** [comment]
![image](https://user-images.githubusercontent.com/30961255/103587493-49565400-4edf-11eb-82e0-e5b4d4e637d6.png)
I couldnt find the message/giverway or anything

**Comment by Vedza** [comment]
Can you send me your discord pls ?

**Comment by hairyfred** [comment]
hairyfred#4914

**Comment by hairyfred** [comment]
Very Unique stituation
Welcome bot mentions nitro

**Comment by Vedza** [comment]
a9e39d4
