### ISSUE TITLE
heroku build failed

### ISSUE THREAD

**Issue by nadfe** [Vedza/NitroSniperGo#76]
i get this error

-----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/go.tgz
       More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
 !     Push failed

**Comment by Vedza** [comment]
Hey,
Did you just click on the "deploy to heroku" button or did you do something else ?

**Comment by nadfe** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/62165074/103671820-6f184300-4f49-11eb-948f-5a8b6a2329f3.png)

I filled out that info and pressed deploy that's it

**Comment by Vedza** [comment]
Can you send me your discord so when can figure out where the problem come from ?

**Comment by nadfe** [comment]
Nadfe#0005
