### ISSUE TITLE
Can someone help me!

### ISSUE THREAD

**Issue by Captain-Piggy** [Vedza/NitroSniperGo#77]
Hy, i'm new with Heroku and everytime i try to launch (I click the button to open app) it just says that there is an error. And i'm new in codding. Please help to make the sniper work. Thx

(https://user-images.githubusercontent.com/77025347/103696752-ea3f2080-4f6c-11eb-8788-53e6c465c5a3.PNG)

**Comment by Vedza** [comment]
hi, you must go to resources and enable worker.
Then go to logs and you'll see it running

**Comment by Captain-Piggy** [comment]
Hey sorry to disturb you but i can't make it run.

**Comment by Captain-Piggy** [comment]
the worker*

**Comment by Captain-Piggy** [comment]
oh its working. Somehow i enabled it. Thank YOUUU
