### ISSUE TITLE
Option to only snipe on alt accounts

### ISSUE THREAD

**Issue by hairyfred** [Vedza/NitroSniperGo#80]
An option to allow only snipe codes/links on alt accounts then redeem them on main

**Comment by fdanielski946** [comment]
that will make the sniper way slower and it will render it useless lul

**Comment by hairyfred** [comment]
> that will make the sniper way slower and it will render it useless lul

The alt tokens find the codes/links , there checked woth main token , dosnt make a speed difference

**Comment by Vedza** [comment]
I don't understand why this would be better, would you please explain ?

**Comment by hairyfred** [comment]
> that will make the sniper way slower and it will render it useless lul

The alt tokens find the codes/links , there checked woth main token , dosnt make a speed difference

> I don't understand why this would be better, could you please explain why this might be a good feature?

If the sniper is looking on your account for codes discord gives your account a hidden status (signed in on web) that other users can see using plugins , just makes it more stealth for your main token

**Comment by Vedza** [comment]
Or the sniper can change status if you want.

```go
_, _ = dg.UserUpdateStatus(discordgo.StatusInvisible)

// Replace StatusInvisible by StatusDoNotDisturb, StatusIdle, StatusOffline or StatusOnline
```
This probably bypass hidden status.
But this will also change your status if you're on your computer.

**Comment by hairyfred** [comment]
> Or the sniper can change status if you want.
> 
> ```go
> _, _ = dg.UserUpdateStatus(discordgo.StatusInvisible)
> 
> // Replace StatusInvisible by StatusDoNotDisturb, StatusIdle, StatusOffline or StatusOnline
> ```
> 
> This probably bypass hidden status.
> But this will also change your status if you're on your computer.

Rather not have a satatus change , its not a huge issue just I know im not the only one using hidden status plugins for an idea of how many people are selfbotting (doubt that many people r actually using discord via web)

**Comment by Vedza** [comment]
I just updated the sniper with this feature
