### ISSUE TITLE
i cant open the nitrosniper.exe

### ISSUE THREAD

**Issue by JustWai** [Vedza/NitroSniperGo#82]
y

**Comment by Vedza** [comment]
You must edit `settings.json`before opening it.

**Comment by JustWai** [comment]
> You must edit `settings.json`before opening it.

wut to edit, do u have a tutorial vid or sth.

**Comment by Vedza** [comment]
Just read here https://github.com/Vedza/NitroSniperGo

**Comment by brams1441** [comment]
![image](https://user-images.githubusercontent.com/63436162/104027915-5e293500-51c8-11eb-90a5-85827fabe48b.png)
