### ISSUE TITLE
(Suggestion) Could you add in the READE.ME how you can update the heroku app?

### ISSUE THREAD

**Issue by brams1441** [Vedza/NitroSniperGo#83]

**Comment by Vedza** [comment]
If you want to pull change from GitHub to Heroku it's actually faster to redeploy.
https://stackoverflow.com/questions/28737548/how-to-update-an-heroku-app-created-using-github-deploy-to-heroku-button

**Comment by brams1441** [comment]
Okay, thanks for the stackoverflow. Ill just redeploy since its faster!
