### ISSUE TITLE
closes when i open the exe file even tho i have set up the settings

### ISSUE THREAD

**Issue by Meptixx** [Vedza/NitroSniperGo#84]

**Comment by Meptixx** [comment]
do u have an discord so i can contact you?

**Comment by JustWai** [comment]
same, it closes for me even tho i did the settings thing

**Comment by Vedza** [comment]
Give me your discord and I'll add you

**Comment by JustWai** [comment]
> Give me your discord and I'll add you

mine is
Just Wai#4004

**Comment by Meptixx** [comment]
> Give me your discord and I'll add you

sure discord is Si66o#0001
