### ISSUE TITLE
add proxy list

### ISSUE THREAD

**Issue by ve3xone** [Vedza/NitroSniperGo#94]
to reduce the risk of the main account being banned, add the ability to add a proxy list

**Comment by Youniz** [comment]
This will make the sniper really slow and won't make a differnce for the main account.

**Comment by Vedza** [comment]
It wouldn't change anything at all about the chance of being banned as all requests will still be done with the same token. It would actually be worst .
And it would make it too slow. You better use 1/2 alts rather than more with proxies.
