### ISSUE TITLE
Ping Time to Claim

### ISSUE THREAD

**Issue by RocketNinja15** [Vedza/NitroSniperGo#97]
This would say the ping time every time it tried to claim,

Attempted to claim code in 121ms 
or something like that.

**Comment by Vedza** [comment]
I'm not going to add delay cause people will compare it to other sniper which doesn't make any sense because they're either fake or not taken between the same steps as I would.

**Comment by RocketNinja15** [comment]
@Vedza i understand that, but i think you should add it, but have it disabled automatically... you can enable it in the settings. 90% of users wont know to turn that on or the use for it. Im just curious the time difference between heroku, locally, and just time in general

This is a piece of code from:  Fweak/CodeClaimer  On how to do it.......(.js)



async function redeemNitro(code, channelId, startTime) {
    const request = await post(`https://discord.com/api/v8/entitlements/gift-codes/${code}/redeem`,
        {
            channel_id: channelId,
            payment_source_id: null
        },
        {
            headers: {
                'Authorization': config.token,
                'X-Super-Properties': 'eyJvcyI6IldpbmRvd3MiLCJicm93c2VyIjoiQ2hyb21lIiwiZGV2aWNlIjoiIiwiYnJvd3Nlcl91c2VyX2FnZW50IjoiTW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzg3LjAuMC4wIFNhZmFyaS81MzcuMzYiLCJicm93c2VyX3ZlcnNpb24iOiI4Ny4wLjAuMCIsIm9zX3ZlcnNpb24iOiIxMCIsInJlZmVycmVyIjoiIiwicmVmZXJyaW5nX2RvbWFpbiI6IiIsInJlZmVycmVyX2N1cnJlbnQiOiIiLCJyZWZlcnJpbmdfZG9tYWluX2N1cnJlbnQiOiIiLCJyZWxlYXNlX2NoYW5uZWwiOiJzdGFibGUiLCJjbGllbnRfYnVpbGRfbnVtYmVyIjo3MzgwMSwiY2xpZW50X2V2ZW50X3NvdXJjZSI6bnVsbH0=',
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
                'Content-Type': 'application/json'
            }
        }
    ).catch(() => { });

    if (request && request.status < 400) return console.log(`${chalk.green("CLAIMED")} ${code} : .${(new Date() - startTime)}ms`);

    return console.log(`${Chalk.redBright("INVALID")} ${code} - Invalid Gift Code : .${(new Date() - startTime)}ms`);
};

**Comment by Vedza** [comment]
Ok I'll add this in the settings then, and don't worry I know how to do it lol.

**Comment by Vedza** [comment]
Available on branch delay
![image](https://user-images.githubusercontent.com/28839427/104822411-80fbbf00-5842-11eb-9805-2e18ed6c741d.png)

**Comment by RocketNinja15** [comment]
@Vedza epic :)
