### ISSUE TITLE
Rate limited

### ISSUE THREAD

**Issue by Tasnemo** [Vedza/NitroSniperGo#98]
Whenever the application snipes a code it says its rate limited but it still says it sniped.
18:25:37 [-] Tasnemo sniped code: Ue7ndfUV3KPEHDEXEMGWhbpr from !             Samier#9999 [Flamin | 🎄 > 🎁・drops]
18:25:37 [?] You are being rate limited.

**Comment by Vedza** [comment]
Sniped just mean the sniper found a gift link, it doesn't mean it was applied to you raccount

**Comment by Tasnemo** [comment]
But why does it rate limit?

**Comment by Tasnemo** [comment]
And is it avoidable

**Comment by Vedza** [comment]
It happens because the servers you're on drop too many Nitros, which are probably fake. Sorry you can't do anything, the bot do its best to avoid that detecting duplicate and fake code
